export default [
  {
   "Question_ID": 3,
   "Question_Title": "Name An Occupation That Would Never drive A Small Car.",
   "Answer_1": "Bus Driver",
   "Answer_1_Points": 35,
   "Answer_2": "Trucker",
   "Answer_2_Points": 34,
   "Answer_3": "Limo Driver",
   "Answer_3_Points": 13,
   "Answer_4": "Fireman",
   "Answer_4_Points": 5,
   "Answer_5": "Postal delivery",
   "Answer_5_Points": 4,
   "Answer_6": "Construction Worker",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 4,
   "Question_Title": "Name A Skill That A Person’s Resume Might Claim They’re Better At Than They Really Are.",
   "Answer_1": "Typing",
   "Answer_1_Points": 28,
   "Answer_2": "Working Hard",
   "Answer_2_Points": 23,
   "Answer_3": "Communication",
   "Answer_3_Points": 20,
   "Answer_4": "Sales",
   "Answer_4_Points": 6,
   "Answer_5": "Customer Service",
   "Answer_5_Points": 5,
   "Answer_6": "Foreign Language",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 5,
   "Question_Title": "Name A Christmas Show That Is On TV Every Year.",
   "Answer_1": "Rudolph",
   "Answer_1_Points": 25,
   "Answer_2": "Christmas Story",
   "Answer_2_Points": 15,
   "Answer_3": "Frosty",
   "Answer_3_Points": 12,
   "Answer_4": "Grinch",
   "Answer_4_Points": 11,
   "Answer_5": "A Wonderful Life",
   "Answer_5_Points": 10,
   "Answer_6": "Home Alone",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 6,
   "Question_Title": "Name A Place Where Most Americans Go At Least Once For Vacation",
   "Answer_1": "Disneyland/World",
   "Answer_1_Points": 45,
   "Answer_2": "Hawii",
   "Answer_2_Points": 35,
   "Answer_3": "Las Vegas",
   "Answer_3_Points": 6,
   "Answer_4": "Mexico",
   "Answer_4_Points": 5,
   "Answer_5": "Grand Canyon",
   "Answer_5_Points": 4,
   "Answer_6": "New York City",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 10,
   "Question_Title": "In What Place Would You Not want To Be Seated Next To Someone With An Annoying Laugh",
   "Answer_1": "Movies",
   "Answer_1_Points": 38,
   "Answer_2": "Airplane",
   "Answer_2_Points": 27,
   "Answer_3": "Church",
   "Answer_3_Points": 13,
   "Answer_4": "Comedy Club",
   "Answer_4_Points": 8,
   "Answer_5": "Restaurant",
   "Answer_5_Points": 5,
   "Answer_6": "Bus",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 11,
   "Question_Title": "Name Something You Are Embarrassed To Do In Front Of People At The Gym",
   "Answer_1": "Change Clothes",
   "Answer_1_Points": 33,
   "Answer_2": "Shower",
   "Answer_2_Points": 25,
   "Answer_3": "Pass Gas",
   "Answer_3_Points": 16,
   "Answer_4": "Run",
   "Answer_4_Points": 11,
   "Answer_5": "Stretch/Bend Over",
   "Answer_5_Points": 6,
   "Answer_6": "Dance",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 12,
   "Question_Title": "Tell Me Something About A Boy’s Appearance That Might Make his Date’s Disapprove Of Him",
   "Answer_1": "Long Hair",
   "Answer_1_Points": 28,
   "Answer_2": "Tattoos",
   "Answer_2_Points": 27,
   "Answer_3": "Inappropriate dress",
   "Answer_3_Points": 20,
   "Answer_4": "Piercings",
   "Answer_4_Points": 17,
   "Answer_5": "Dirty/Unkempt",
   "Answer_5_Points": 3,
   "Answer_6": "Facial Hair",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 13,
   "Question_Title": "Name Something A Child Might Carry Along Everywhere",
   "Answer_1": "Blanket",
   "Answer_1_Points": 27,
   "Answer_2": "Toy",
   "Answer_2_Points": 26,
   "Answer_3": "Teddy Bear",
   "Answer_3_Points": 22,
   "Answer_4": "Doll",
   "Answer_4_Points": 15,
   "Answer_5": "Bottle",
   "Answer_5_Points": 5,
   "Answer_6": "Pacifier",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 15,
   "Question_Title": "Name Something Your Spouse Might Get Mad At You for Doing Too Much",
   "Answer_1": "Talking",
   "Answer_1_Points": 27,
   "Answer_2": "Shopping/Spending",
   "Answer_2_Points": 21,
   "Answer_3": "Drinking",
   "Answer_3_Points": 18,
   "Answer_4": "Sleeping",
   "Answer_4_Points": 16,
   "Answer_5": "Spending Money",
   "Answer_5_Points": 9,
   "Answer_6": "Watching TV",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 16,
   "Question_Title": "What Kind Of Gift Would You Get Somebody That Spends A Lot Of Time At The Beach",
   "Answer_1": "Towel",
   "Answer_1_Points": 45,
   "Answer_2": "Bathing Suit",
   "Answer_2_Points": 17,
   "Answer_3": "Sun Screen",
   "Answer_3_Points": 10,
   "Answer_4": "Umbrella",
   "Answer_4_Points": 10,
   "Answer_5": "Sunglasses",
   "Answer_5_Points": 8,
   "Answer_6": "Beach Chair",
   "Answer_6_Points": 7
 },
 {
   "Question_ID": 17,
   "Question_Title": "Name Something Millionaires Might Shop For Just For Fun",
   "Answer_1": "cars",
   "Answer_1_Points": 71,
   "Answer_2": "Clothes",
   "Answer_2_Points": 10,
   "Answer_3": "Houses",
   "Answer_3_Points": 9,
   "Answer_4": "Jewlery",
   "Answer_4_Points": 3,
   "Answer_5": "Plane",
   "Answer_5_Points": 3,
   "Answer_6": "boat",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 18,
   "Question_Title": "Name An Item That Stores Probably Have A Hard Time Selling After Christmas",
   "Answer_1": "Trees",
   "Answer_1_Points": 37,
   "Answer_2": "Ornaments",
   "Answer_2_Points": 19,
   "Answer_3": "Toys",
   "Answer_3_Points": 11,
   "Answer_4": "Lights",
   "Answer_4_Points": 8,
   "Answer_5": "Wrapping Paper",
   "Answer_5_Points": 7,
   "Answer_6": "Christmas Cards",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 19,
   "Question_Title": "Name Something You Do In Front Of A Mirror You Wouldn’t Want Anyone To See",
   "Answer_1": "Pop A Pimple",
   "Answer_1_Points": 14,
   "Answer_2": "Look At Your Body",
   "Answer_2_Points": 9,
   "Answer_3": "Dance",
   "Answer_3_Points": 8,
   "Answer_4": "Undress",
   "Answer_4_Points": 6,
   "Answer_5": "Pluck eyebrows",
   "Answer_5_Points": 6,
   "Answer_6": "Clip Nose Hairs",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 20,
   "Question_Title": "Name Something That You Can Tell Is Fake In A Cheesy Movie",
   "Answer_1": "Blood",
   "Answer_1_Points": 50,
   "Answer_2": "Love Scenes",
   "Answer_2_Points": 13,
   "Answer_3": "Scenery",
   "Answer_3_Points": 12,
   "Answer_4": "Acting",
   "Answer_4_Points": 10,
   "Answer_5": "Monsters",
   "Answer_5_Points": 6,
   "Answer_6": "Fight Scenes",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 22,
   "Question_Title": "name A fear parents Have For Their Child, When She Moves Out Of The House",
   "Answer_1": "Money",
   "Answer_1_Points": 35,
   "Answer_2": "Drugs",
   "Answer_2_Points": 23,
   "Answer_3": "Death",
   "Answer_3_Points": 14,
   "Answer_4": "Safety",
   "Answer_4_Points": 11,
   "Answer_5": "Coming Back",
   "Answer_5_Points": 10,
   "Answer_6": "Lonely",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 23,
   "Question_Title": "When Sitting Close To A Date, What Clue Might They Give That They Like You",
   "Answer_1": "Holds Your hand",
   "Answer_1_Points": 28,
   "Answer_2": "kisses You",
   "Answer_2_Points": 25,
   "Answer_3": "Smiling",
   "Answer_3_Points": 21,
   "Answer_4": "Arm Around You",
   "Answer_4_Points": 12,
   "Answer_5": "Move Closer",
   "Answer_5_Points": 7,
   "Answer_6": "Looking At You",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 24,
   "Question_Title": "Name An Instance When You Fake A Smile",
   "Answer_1": "Having A Photo Taken",
   "Answer_1_Points": 34,
   "Answer_2": "Hear A Bad Joke",
   "Answer_2_Points": 18,
   "Answer_3": "Job Interview",
   "Answer_3_Points": 13,
   "Answer_4": "Upset",
   "Answer_4_Points": 12,
   "Answer_5": "Meeting New People",
   "Answer_5_Points": 12,
   "Answer_6": "Nervous",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 25,
   "Question_Title": "Name A Sign You’re At A Really Cheap Birthday party",
   "Answer_1": "No Cake",
   "Answer_1_Points": 22,
   "Answer_2": "No food",
   "Answer_2_Points": 17,
   "Answer_3": "No Decorations",
   "Answer_3_Points": 7,
   "Answer_4": "No favors",
   "Answer_4_Points": 6,
   "Answer_5": "No Presents",
   "Answer_5_Points": 5,
   "Answer_6": "No cards",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 26,
   "Question_Title": "Name Something That Young Children Memorize",
   "Answer_1": "Alphabet",
   "Answer_1_Points": 62,
   "Answer_2": "Spell Their Name",
   "Answer_2_Points": 13,
   "Answer_3": "Phone Number",
   "Answer_3_Points": 8,
   "Answer_4": "Address",
   "Answer_4_Points": 4,
   "Answer_5": "Nursery Rhymes",
   "Answer_5_Points": 4,
   "Answer_6": "Pledge Of Allegiance",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 28,
   "Question_Title": "Other than Acting, Name A Profession That Celebrity Actors Might Take Up",
   "Answer_1": "Singing",
   "Answer_1_Points": 61,
   "Answer_2": "Directing",
   "Answer_2_Points": 11,
   "Answer_3": "Modeling",
   "Answer_3_Points": 10,
   "Answer_4": "Fashion design",
   "Answer_4_Points": 9,
   "Answer_5": "Politics",
   "Answer_5_Points": 3,
   "Answer_6": "Spokeperson",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 30,
   "Question_Title": "Name Something You Should Never Wear As The Guest At Someone’s Wedding",
   "Answer_1": "White Dress",
   "Answer_1_Points": 28,
   "Answer_2": "All black",
   "Answer_2_Points": 24,
   "Answer_3": "Shorts",
   "Answer_3_Points": 15,
   "Answer_4": "Jeans",
   "Answer_4_Points": 12,
   "Answer_5": "Cap",
   "Answer_5_Points": 5,
   "Answer_6": "T Shirt",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 32,
   "Question_Title": "Name A Movie Or TV Show That Has The word ‘Diary/Diaries’ In The Title",
   "Answer_1": "…Mad Black Woman",
   "Answer_1_Points": 29,
   "Answer_2": "Diary Of Ann Frank",
   "Answer_2_Points": 26,
   "Answer_3": "Princess Diaries",
   "Answer_3_Points": 19,
   "Answer_4": "Bridgette Jones’",
   "Answer_4_Points": 9,
   "Answer_5": "Diary Of A Wimpy Kid",
   "Answer_5_Points": 8,
   "Answer_6": "Vampire Diaries",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 35,
   "Question_Title": "Name A Job Where It Would Be Okay To Yell At Work",
   "Answer_1": "construction",
   "Answer_1_Points": 43,
   "Answer_2": "Sports",
   "Answer_2_Points": 31,
   "Answer_3": "Teacher",
   "Answer_3_Points": 8,
   "Answer_4": "Police",
   "Answer_4_Points": 6,
   "Answer_5": "Stock Broker",
   "Answer_5_Points": 5,
   "Answer_6": "Auctioneer",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 36,
   "Question_Title": "Name A Sport In Which Participants Use A Specific Kind Of Headwear",
   "Answer_1": "Football",
   "Answer_1_Points": 36,
   "Answer_2": "Hockey",
   "Answer_2_Points": 18,
   "Answer_3": "Baseball",
   "Answer_3_Points": 18,
   "Answer_4": "Swimming",
   "Answer_4_Points": 10,
   "Answer_5": "Wrestling",
   "Answer_5_Points": 5,
   "Answer_6": "Boxing",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 37,
   "Question_Title": "What Do People Do That Could Get Them Kicked Out Of A Museum",
   "Answer_1": "touch The Art",
   "Answer_1_Points": 33,
   "Answer_2": "Run",
   "Answer_2_Points": 15,
   "Answer_3": "Steal",
   "Answer_3_Points": 14,
   "Answer_4": "Yell",
   "Answer_4_Points": 12,
   "Answer_5": "Bring Food In",
   "Answer_5_Points": 10,
   "Answer_6": "Break Something",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 39,
   "Question_Title": "Name Something A Child Might Never Do If They weren’t Forced To",
   "Answer_1": "Brush Teeth",
   "Answer_1_Points": 27,
   "Answer_2": "Eat Vegetable",
   "Answer_2_Points": 18,
   "Answer_3": "School/Homework",
   "Answer_3_Points": 17,
   "Answer_4": "Bathe",
   "Answer_4_Points": 11,
   "Answer_5": "Go To Bed",
   "Answer_5_Points": 10,
   "Answer_6": "Clean",
   "Answer_6_Points": 10
 },
 {
   "Question_ID": 40,
   "Question_Title": "Name Something That it’s Hard To Do While Listening To Music",
   "Answer_1": "Read",
   "Answer_1_Points": 30,
   "Answer_2": "Have A Conversation",
   "Answer_2_Points": 27,
   "Answer_3": "Watch TV",
   "Answer_3_Points": 18,
   "Answer_4": "Study",
   "Answer_4_Points": 11,
   "Answer_5": "Fall Asleep",
   "Answer_5_Points": 7,
   "Answer_6": "Concentrate",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 42,
   "Question_Title": "aside From Animals, Name Something People Hunt For.",
   "Answer_1": "bargains",
   "Answer_1_Points": 38,
   "Answer_2": "treasure",
   "Answer_2_Points": 16,
   "Answer_3": "Easter Eggs",
   "Answer_3_Points": 14,
   "Answer_4": "Lost Keys",
   "Answer_4_Points": 11,
   "Answer_5": "Job",
   "Answer_5_Points": 8,
   "Answer_6": "Dates",
   "Answer_6_Points": 7
 },
 {
   "Question_ID": 43,
   "Question_Title": "name Something A Celebrity Hopes Won’t Happen While On Stage To Accept An Award",
   "Answer_1": "Fall",
   "Answer_1_Points": 43,
   "Answer_2": "Forget Speech",
   "Answer_2_Points": 22,
   "Answer_3": "Loose Voice",
   "Answer_3_Points": 11,
   "Answer_4": "Faint",
   "Answer_4_Points": 6,
   "Answer_5": "Cry",
   "Answer_5_Points": 4,
   "Answer_6": "Drop Award",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 44,
   "Question_Title": "Name Something You Do In A Booth",
   "Answer_1": "Kiss",
   "Answer_1_Points": 17,
   "Answer_2": "Talk On Phone",
   "Answer_2_Points": 16,
   "Answer_3": "Have Picture Taken",
   "Answer_3_Points": 15,
   "Answer_4": "Vote",
   "Answer_4_Points": 14,
   "Answer_5": "Sell Tickets",
   "Answer_5_Points": 12,
   "Answer_6": "Eat",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 45,
   "Question_Title": "name something You Often Feel Sleepy while Doing",
   "Answer_1": "Reading",
   "Answer_1_Points": 48,
   "Answer_2": "Driving",
   "Answer_2_Points": 27,
   "Answer_3": "Watching Tv",
   "Answer_3_Points": 10,
   "Answer_4": "Working",
   "Answer_4_Points": 5,
   "Answer_5": "Homework",
   "Answer_5_Points": 4,
   "Answer_6": "Eating",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 47,
   "Question_Title": "Name A Job Where Employees Must get Tired Arms",
   "Answer_1": "Construction",
   "Answer_1_Points": 29,
   "Answer_2": "Movers",
   "Answer_2_Points": 24,
   "Answer_3": "parcle Delivery",
   "Answer_3_Points": 18,
   "Answer_4": "Hair dresser",
   "Answer_4_Points": 12,
   "Answer_5": "Traffic Cop",
   "Answer_5_Points": 5,
   "Answer_6": "Food server",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 49,
   "Question_Title": "name A Way You Might Be Able to Tell Your Baby Is really An Alien",
   "Answer_1": "Strange Appearance",
   "Answer_1_Points": 19,
   "Answer_2": "Weird Eyes",
   "Answer_2_Points": 18,
   "Answer_3": "Large Ears",
   "Answer_3_Points": 7,
   "Answer_4": "Antennas",
   "Answer_4_Points": 6,
   "Answer_5": "Speech",
   "Answer_5_Points": 6,
   "Answer_6": "He can Fly",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 50,
   "Question_Title": "What Might somebody Do That Would Annoy Fellow Theater-Goers At A Play?",
   "Answer_1": "Talk Loudly",
   "Answer_1_Points": 80,
   "Answer_2": "Use Phone",
   "Answer_2_Points": 6,
   "Answer_3": "Cough",
   "Answer_3_Points": 3,
   "Answer_4": "Laugh",
   "Answer_4_Points": 3,
   "Answer_5": "Snore",
   "Answer_5_Points": 3,
   "Answer_6": "Heckle",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 51,
   "Question_Title": "Name Something A Magician Might Make Disappear",
   "Answer_1": "Rabbit",
   "Answer_1_Points": 43,
   "Answer_2": "Assistant/Spectator",
   "Answer_2_Points": 36,
   "Answer_3": "Bird",
   "Answer_3_Points": 7,
   "Answer_4": "Money",
   "Answer_4_Points": 4,
   "Answer_5": "Flowers",
   "Answer_5_Points": 3,
   "Answer_6": "her/himself",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 52,
   "Question_Title": "Name Something A Slob Might Never Clean",
   "Answer_1": "Bedroom",
   "Answer_1_Points": 46,
   "Answer_2": "bathroom",
   "Answer_2_Points": 25,
   "Answer_3": "kitchen",
   "Answer_3_Points": 8,
   "Answer_4": "Car",
   "Answer_4_Points": 7,
   "Answer_5": "Clothes",
   "Answer_5_Points": 7,
   "Answer_6": "Himself/Herself",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 53,
   "Question_Title": "Name A Popular Pick Up Line",
   "Answer_1": "Do I know You",
   "Answer_1_Points": 33,
   "Answer_2": "Hey Baby",
   "Answer_2_Points": 28,
   "Answer_3": "What’s Your Sign",
   "Answer_3_Points": 12,
   "Answer_4": "Fall Form Heaven",
   "Answer_4_Points": 9,
   "Answer_5": "Come Here Often",
   "Answer_5_Points": 6,
   "Answer_6": "How You Doing",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 54,
   "Question_Title": "By What Method Might A Woman Make The Announcement That She’s Pregnant",
   "Answer_1": "Over Dinner",
   "Answer_1_Points": 27,
   "Answer_2": "With A Party",
   "Answer_2_Points": 20,
   "Answer_3": "In An Email",
   "Answer_3_Points": 15,
   "Answer_4": "Send Out Announcements",
   "Answer_4_Points": 12,
   "Answer_5": "By Phone",
   "Answer_5_Points": 8,
   "Answer_6": "In Person",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 55,
   "Question_Title": "What Might An Adult Wear That Has His Name On It?",
   "Answer_1": "Shirt/Uniform",
   "Answer_1_Points": 46,
   "Answer_2": "Name Tag",
   "Answer_2_Points": 26,
   "Answer_3": "Jewlery",
   "Answer_3_Points": 11,
   "Answer_4": "Jersey",
   "Answer_4_Points": 5,
   "Answer_5": "Belt",
   "Answer_5_Points": 4,
   "Answer_6": "Jacket",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 57,
   "Question_Title": "Name Something Teens May Be Afraid Of When Moving Away To College",
   "Answer_1": "Expenses",
   "Answer_1_Points": 41,
   "Answer_2": "Being Alone",
   "Answer_2_Points": 25,
   "Answer_3": "Leaving Home",
   "Answer_3_Points": 12,
   "Answer_4": "Making New Friends",
   "Answer_4_Points": 5,
   "Answer_5": "Difficult Classes",
   "Answer_5_Points": 4,
   "Answer_6": "New Roommate",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 58,
   "Question_Title": "name A Place You’d Visit More Often If It wasn’t So Crowded There",
   "Answer_1": "Mall",
   "Answer_1_Points": 31,
   "Answer_2": "Zoo",
   "Answer_2_Points": 22,
   "Answer_3": "Bar/Club",
   "Answer_3_Points": 14,
   "Answer_4": "Disney World",
   "Answer_4_Points": 13,
   "Answer_5": "Beach",
   "Answer_5_Points": 9,
   "Answer_6": "Park",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 59,
   "Question_Title": "Name A Place Where A Mom Might Go When She Says, ” I Need Peace And Quiet.”",
   "Answer_1": "Her Bedroom",
   "Answer_1_Points": 38,
   "Answer_2": "Take A Bath",
   "Answer_2_Points": 30,
   "Answer_3": "Spa",
   "Answer_3_Points": 11,
   "Answer_4": "Place Of worship",
   "Answer_4_Points": 9,
   "Answer_5": "Library",
   "Answer_5_Points": 6,
   "Answer_6": "Park",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 60,
   "Question_Title": "Name Something Around The House You Might Keep Spare Batteries For",
   "Answer_1": "Flashlight",
   "Answer_1_Points": 42,
   "Answer_2": "Remote Control",
   "Answer_2_Points": 26,
   "Answer_3": "Radio",
   "Answer_3_Points": 11,
   "Answer_4": "Toys",
   "Answer_4_Points": 8,
   "Answer_5": "Music Player",
   "Answer_5_Points": 6,
   "Answer_6": "Portable Videogame",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 61,
   "Question_Title": "What Is The First Thing You Would Do If You Won A Million Dollars",
   "Answer_1": "Buy A House",
   "Answer_1_Points": 48,
   "Answer_2": "Buy A Car",
   "Answer_2_Points": 18,
   "Answer_3": "Vacation",
   "Answer_3_Points": 11,
   "Answer_4": "Shopping Spree",
   "Answer_4_Points": 8,
   "Answer_5": "Pay Bills",
   "Answer_5_Points": 7,
   "Answer_6": "Quit Job",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 62,
   "Question_Title": "Name something That’s forbidden In Most Swimming Pools",
   "Answer_1": "Peeing",
   "Answer_1_Points": 41,
   "Answer_2": "Diving",
   "Answer_2_Points": 21,
   "Answer_3": "Street Clothes",
   "Answer_3_Points": 12,
   "Answer_4": "Nudity",
   "Answer_4_Points": 9,
   "Answer_5": "Eating",
   "Answer_5_Points": 7,
   "Answer_6": "Rafts",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 63,
   "Question_Title": "What Do Tourists Ride In Or On, That Makes Them Stand Out?",
   "Answer_1": "Tour Bus",
   "Answer_1_Points": 46,
   "Answer_2": "Bicycle For 2",
   "Answer_2_Points": 15,
   "Answer_3": "Rental Cars",
   "Answer_3_Points": 13,
   "Answer_4": "Taxi",
   "Answer_4_Points": 9,
   "Answer_5": "Carriage",
   "Answer_5_Points": 4,
   "Answer_6": "Rickshaw",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 64,
   "Question_Title": "Name something Many People Would Love To Live Next To",
   "Answer_1": "Swimming Area",
   "Answer_1_Points": 52,
   "Answer_2": "Park",
   "Answer_2_Points": 16,
   "Answer_3": "Shopping District",
   "Answer_3_Points": 15,
   "Answer_4": "Bar",
   "Answer_4_Points": 6,
   "Answer_5": "Celebrity’s Home",
   "Answer_5_Points": 5,
   "Answer_6": "School",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 65,
   "Question_Title": "At which Type Of Place Would You Be Surprised To See A Neon Sign Hanging In The Window",
   "Answer_1": "Place Of Worship",
   "Answer_1_Points": 54,
   "Answer_2": "My House",
   "Answer_2_Points": 27,
   "Answer_3": "Hospital",
   "Answer_3_Points": 6,
   "Answer_4": "Dentist’s Office",
   "Answer_4_Points": 3,
   "Answer_5": "Library",
   "Answer_5_Points": 3,
   "Answer_6": "School",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 66,
   "Question_Title": "Name a Meal You’d Never Serve At a Fancy Party",
   "Answer_1": "Pizza",
   "Answer_1_Points": 40,
   "Answer_2": "Hot Dog",
   "Answer_2_Points": 32,
   "Answer_3": "Hamburger",
   "Answer_3_Points": 11,
   "Answer_4": "Spaghetti",
   "Answer_4_Points": 6,
   "Answer_5": "Meatloaf",
   "Answer_5_Points": 5,
   "Answer_6": "Sloppy Joe",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 68,
   "Question_Title": "Name Something A Fan Might Collect From Their favorite Singer",
   "Answer_1": "Autograph",
   "Answer_1_Points": 52,
   "Answer_2": "Albums",
   "Answer_2_Points": 12,
   "Answer_3": "Hair",
   "Answer_3_Points": 8,
   "Answer_4": "Posters",
   "Answer_4_Points": 7,
   "Answer_5": "Photos",
   "Answer_5_Points": 7,
   "Answer_6": "T Shirt",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 70,
   "Question_Title": "name Something You Carry with You Just In Case, But Hate to Get Stuck Carrying",
   "Answer_1": "Jacket",
   "Answer_1_Points": 31,
   "Answer_2": "Purse/Wallet",
   "Answer_2_Points": 19,
   "Answer_3": "Cell Phone",
   "Answer_3_Points": 17,
   "Answer_4": "Camera",
   "Answer_4_Points": 14,
   "Answer_5": "Umbrella",
   "Answer_5_Points": 12,
   "Answer_6": "Water Bottle",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 71,
   "Question_Title": "Name Something Men Probably Lie About Most",
   "Answer_1": "Age",
   "Answer_1_Points": 42,
   "Answer_2": "Being Single",
   "Answer_2_Points": 20,
   "Answer_3": "Income",
   "Answer_3_Points": 19,
   "Answer_4": "Success With Women",
   "Answer_4_Points": 6,
   "Answer_5": "Job Title",
   "Answer_5_Points": 5,
   "Answer_6": "Weight",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 72,
   "Question_Title": "Name Something People Proudly Share On Facebook",
   "Answer_1": "Pictures",
   "Answer_1_Points": 53,
   "Answer_2": "Info. On Kids",
   "Answer_2_Points": 12,
   "Answer_3": "Age",
   "Answer_3_Points": 10,
   "Answer_4": "Real Name",
   "Answer_4_Points": 10,
   "Answer_5": "Relationship Status",
   "Answer_5_Points": 5,
   "Answer_6": "Who friends Are",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 73,
   "Question_Title": "Name Something You Wouldn’t Want Your date To Talk Too Much About",
   "Answer_1": "Past relationships",
   "Answer_1_Points": 37,
   "Answer_2": "Intimacy",
   "Answer_2_Points": 23,
   "Answer_3": "Him/Herself",
   "Answer_3_Points": 14,
   "Answer_4": "Monsy",
   "Answer_4_Points": 9,
   "Answer_5": "Family",
   "Answer_5_Points": 4,
   "Answer_6": "Work",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 77,
   "Question_Title": "Name A Place You Would Go With Your Wife Just To Make Her Stop Nagging",
   "Answer_1": "Shopping Center",
   "Answer_1_Points": 36,
   "Answer_2": "Restaurant",
   "Answer_2_Points": 23,
   "Answer_3": "Movie Theater",
   "Answer_3_Points": 17,
   "Answer_4": "Place Of Worship",
   "Answer_4_Points": 8,
   "Answer_5": "Hawii",
   "Answer_5_Points": 5,
   "Answer_6": "Ballet",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 78,
   "Question_Title": "Name Something You Do After returning Home From A Long Vacation",
   "Answer_1": "Sleep",
   "Answer_1_Points": 32,
   "Answer_2": "Unpack",
   "Answer_2_Points": 21,
   "Answer_3": "Eating Sweets",
   "Answer_3_Points": 18,
   "Answer_4": "Laundry",
   "Answer_4_Points": 10,
   "Answer_5": "Shower",
   "Answer_5_Points": 6,
   "Answer_6": "Check Mail",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 79,
   "Question_Title": "Name An Employee You’d Find At A Fancy Hotel, But Not At A Budget Motel",
   "Answer_1": "Concierge",
   "Answer_1_Points": 32,
   "Answer_2": "Bellhop",
   "Answer_2_Points": 22,
   "Answer_3": "Valet",
   "Answer_3_Points": 17,
   "Answer_4": "Doorperson",
   "Answer_4_Points": 12,
   "Answer_5": "Room Service",
   "Answer_5_Points": 8,
   "Answer_6": "Chef",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 81,
   "Question_Title": "Name Something You Would Do In A Public Restroom That You Would Never Do In Your Own Bathroom",
   "Answer_1": "Pee On The Floor",
   "Answer_1_Points": 24,
   "Answer_2": "Pee On The Toilet",
   "Answer_2_Points": 14,
   "Answer_3": "Put Paper On Seat",
   "Answer_3_Points": 12,
   "Answer_4": "Write On Wall",
   "Answer_4_Points": 11,
   "Answer_5": "Leave It Messy",
   "Answer_5_Points": 10,
   "Answer_6": "Don’t flush Toilet",
   "Answer_6_Points": 9
 },
 {
   "Question_ID": 82,
   "Question_Title": "Name Something A Person Might Do In Order To Stay Attractive",
   "Answer_1": "Plastic Surgery",
   "Answer_1_Points": 33,
   "Answer_2": "Exercise",
   "Answer_2_Points": 26,
   "Answer_3": "Wear Makeup",
   "Answer_3_Points": 14,
   "Answer_4": "Diet",
   "Answer_4_Points": 8,
   "Answer_5": "Use Botox",
   "Answer_5_Points": 6,
   "Answer_6": "Dye Hair",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 83,
   "Question_Title": "Name Something Women’s Magazines Give Advice On",
   "Answer_1": "Intimacy",
   "Answer_1_Points": 46,
   "Answer_2": "Romantic Relationships",
   "Answer_2_Points": 24,
   "Answer_3": "Makeup",
   "Answer_3_Points": 6,
   "Answer_4": "Hair",
   "Answer_4_Points": 5,
   "Answer_5": "Keeping Fit",
   "Answer_5_Points": 5,
   "Answer_6": "Fashion",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 89,
   "Question_Title": "Name A Public Place You Immediately Want To Wash Your Hands Immediately After Leaving",
   "Answer_1": "Hospital",
   "Answer_1_Points": 30,
   "Answer_2": "Restaurant",
   "Answer_2_Points": 25,
   "Answer_3": "Zoo",
   "Answer_3_Points": 13,
   "Answer_4": "Shopping Center",
   "Answer_4_Points": 11,
   "Answer_5": "Bar",
   "Answer_5_Points": 8,
   "Answer_6": "Gas station",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 92,
   "Question_Title": "Name Something A resourceful Person Might Use To Hang A Picture If They Didn’t Have A Nail",
   "Answer_1": "Tape",
   "Answer_1_Points": 38,
   "Answer_2": "Tack",
   "Answer_2_Points": 29,
   "Answer_3": "Glue",
   "Answer_3_Points": 12,
   "Answer_4": "Gum",
   "Answer_4_Points": 6,
   "Answer_5": "String",
   "Answer_5_Points": 3,
   "Answer_6": "Hanger",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 93,
   "Question_Title": "Which Olympic Sport Would Be Most Fun To watch Live",
   "Answer_1": "Swimming",
   "Answer_1_Points": 39,
   "Answer_2": "Gymnastics",
   "Answer_2_Points": 21,
   "Answer_3": "Basketball",
   "Answer_3_Points": 15,
   "Answer_4": "Hockey",
   "Answer_4_Points": 9,
   "Answer_5": "Track",
   "Answer_5_Points": 8,
   "Answer_6": "Ice Skating",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 94,
   "Question_Title": "Name A Culture Or Religion That Celebrates A Different New Year Then The West",
   "Answer_1": "Chinese",
   "Answer_1_Points": 54,
   "Answer_2": "Jewish",
   "Answer_2_Points": 26,
   "Answer_3": "Islam",
   "Answer_3_Points": 7,
   "Answer_4": "Japan",
   "Answer_4_Points": 5,
   "Answer_5": "Buddhist",
   "Answer_5_Points": 4,
   "Answer_6": "India",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 95,
   "Question_Title": "Instead Of Get A Job, Name Something A Person Might Do After College",
   "Answer_1": "Travel",
   "Answer_1_Points": 35,
   "Answer_2": "Get Married",
   "Answer_2_Points": 33,
   "Answer_3": "Go Back To School",
   "Answer_3_Points": 12,
   "Answer_4": "Move Back Home",
   "Answer_4_Points": 8,
   "Answer_5": "Party",
   "Answer_5_Points": 5,
   "Answer_6": "Join The Military",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 96,
   "Question_Title": "We Asked 100 Parents: Name Something You’d Tell Your Children To Do First Before Getting Married",
   "Answer_1": "Finish School",
   "Answer_1_Points": 38,
   "Answer_2": "Fall In Love",
   "Answer_2_Points": 26,
   "Answer_3": "Get A Job",
   "Answer_3_Points": 14,
   "Answer_4": "Date Others",
   "Answer_4_Points": 8,
   "Answer_5": "Have Fun",
   "Answer_5_Points": 5,
   "Answer_6": "Live Together",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 97,
   "Question_Title": "Name A Place That Single People Travel To For Its Party Atmosphere",
   "Answer_1": "Las Vegas",
   "Answer_1_Points": 41,
   "Answer_2": "Cancun",
   "Answer_2_Points": 26,
   "Answer_3": "New Oleeans",
   "Answer_3_Points": 14,
   "Answer_4": "New York",
   "Answer_4_Points": 8,
   "Answer_5": "Amsterdam",
   "Answer_5_Points": 4,
   "Answer_6": "Los Angeles",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 98,
   "Question_Title": "Name A Food Or Beverage You Wouldn’t Consume After It’d Been Sitting Out In Hot Weather",
   "Answer_1": "Milk",
   "Answer_1_Points": 40,
   "Answer_2": "Beer",
   "Answer_2_Points": 18,
   "Answer_3": "Soda",
   "Answer_3_Points": 13,
   "Answer_4": "Ice Cream",
   "Answer_4_Points": 10,
   "Answer_5": "Water",
   "Answer_5_Points": 3,
   "Answer_6": "Meat",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 100,
   "Question_Title": "Name Something That Is Rude To Do When Someone Is Taking TO You",
   "Answer_1": "Interupt",
   "Answer_1_Points": 34,
   "Answer_2": "Look Away",
   "Answer_2_Points": 33,
   "Answer_3": "Leave The Room",
   "Answer_3_Points": 10,
   "Answer_4": "Yawn",
   "Answer_4_Points": 7,
   "Answer_5": "Use Cell Phone",
   "Answer_5_Points": 6,
   "Answer_6": "Not Make Eye Contact",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 102,
   "Question_Title": "Name Something Most Parents have Pictures Of Their Child Doing",
   "Answer_1": "Bathing",
   "Answer_1_Points": 29,
   "Answer_2": "Playing",
   "Answer_2_Points": 25,
   "Answer_3": "Eating",
   "Answer_3_Points": 14,
   "Answer_4": "Smile/Laugh",
   "Answer_4_Points": 13,
   "Answer_5": "Sleeping",
   "Answer_5_Points": 13,
   "Answer_6": "Openig Presents",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 103,
   "Question_Title": "Name Something Your House Is Full Of After Christmas",
   "Answer_1": "PRESENTS",
   "Answer_1_Points": 34,
   "Answer_2": "WRAPPING PAPER",
   "Answer_2_Points": 31,
   "Answer_3": "FOOD",
   "Answer_3_Points": 15,
   "Answer_4": "PINE NEEDLES",
   "Answer_4_Points": 6,
   "Answer_5": "BOXES",
   "Answer_5_Points": 5,
   "Answer_6": "PEOPLE",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 105,
   "Question_Title": "Name A Food That’s Baked In The Oven, But Can’t Be Cooked In The Microwave",
   "Answer_1": "Cake",
   "Answer_1_Points": 46,
   "Answer_2": "Chicken",
   "Answer_2_Points": 15,
   "Answer_3": "Bread",
   "Answer_3_Points": 14,
   "Answer_4": "Cookies",
   "Answer_4_Points": 11,
   "Answer_5": "Pie",
   "Answer_5_Points": 8,
   "Answer_6": "Roast",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 106,
   "Question_Title": "Name Something About A Teddy Bear That’s Different From A Real Bear",
   "Answer_1": "Huggable",
   "Answer_1_Points": 29,
   "Answer_2": "Stuffed",
   "Answer_2_Points": 19,
   "Answer_3": "Smaller",
   "Answer_3_Points": 16,
   "Answer_4": "Softer",
   "Answer_4_Points": 12,
   "Answer_5": "No Teeth",
   "Answer_5_Points": 10,
   "Answer_6": "Safe",
   "Answer_6_Points": 7
 },
 {
   "Question_ID": 107,
   "Question_Title": "In The Store, Name A Product That You Might Choose Because It’s Soft",
   "Answer_1": "TOILET PAPER",
   "Answer_1_Points": 35,
   "Answer_2": "BREAD",
   "Answer_2_Points": 23,
   "Answer_3": "PILLOW",
   "Answer_3_Points": 17,
   "Answer_4": "BLANKET",
   "Answer_4_Points": 14,
   "Answer_5": "TOWEL",
   "Answer_5_Points": 4,
   "Answer_6": "SHIRT",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 108,
   "Question_Title": "Besides Swimming, Name Something People Do To Stay Cool In The Summer",
   "Answer_1": "Cold Drinks",
   "Answer_1_Points": 26,
   "Answer_2": "Eat Ice Cream",
   "Answer_2_Points": 18,
   "Answer_3": "Use A Fan",
   "Answer_3_Points": 17,
   "Answer_4": "Cold Shower",
   "Answer_4_Points": 14,
   "Answer_5": "Air COnditioning",
   "Answer_5_Points": 14,
   "Answer_6": "Sit In Shade",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 109,
   "Question_Title": "Name A Drink That Often Comes With A Spoon",
   "Answer_1": "Milkshake",
   "Answer_1_Points": 33,
   "Answer_2": "Coffee",
   "Answer_2_Points": 28,
   "Answer_3": "Tea",
   "Answer_3_Points": 24,
   "Answer_4": "Hot Chocolate",
   "Answer_4_Points": 8,
   "Answer_5": "Root Beer Float",
   "Answer_5_Points": 3,
   "Answer_6": "Slush/Smoothie",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 110,
   "Question_Title": "If You Got A New Puppy, Name Something You’d Teach It",
   "Answer_1": "Sit",
   "Answer_1_Points": 34,
   "Answer_2": "House Training",
   "Answer_2_Points": 20,
   "Answer_3": "Fetch",
   "Answer_3_Points": 19,
   "Answer_4": "Roll Over",
   "Answer_4_Points": 16,
   "Answer_5": "Don’t Bite/Chew",
   "Answer_5_Points": 5,
   "Answer_6": "Stay",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 111,
   "Question_Title": "Name Something That You Would wear To A Wedding In The Dessert",
   "Answer_1": "Sandals",
   "Answer_1_Points": 35,
   "Answer_2": "Bathing Suit",
   "Answer_2_Points": 22,
   "Answer_3": "Sun Dress",
   "Answer_3_Points": 15,
   "Answer_4": "Sun Hat",
   "Answer_4_Points": 10,
   "Answer_5": "Shorts",
   "Answer_5_Points": 7,
   "Answer_6": "Sunscreen",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 112,
   "Question_Title": "Name Something Romantic You Hope To Still Do With Your Partner When You’re 80",
   "Answer_1": "Kiss",
   "Answer_1_Points": 30,
   "Answer_2": "Hold Hands",
   "Answer_2_Points": 27,
   "Answer_3": "Intimacy",
   "Answer_3_Points": 22,
   "Answer_4": "Dance",
   "Answer_4_Points": 9,
   "Answer_5": "Go On Dates",
   "Answer_5_Points": 6,
   "Answer_6": "Take Walks",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 113,
   "Question_Title": "Tell Me A Situation That Makes Just About Everyone Nervous",
   "Answer_1": "Wedding",
   "Answer_1_Points": 27,
   "Answer_2": "Dating",
   "Answer_2_Points": 21,
   "Answer_3": "Job Interview",
   "Answer_3_Points": 16,
   "Answer_4": "Doctor Appt",
   "Answer_4_Points": 13,
   "Answer_5": "Public Speaking",
   "Answer_5_Points": 12,
   "Answer_6": "Taking A Test",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 116,
   "Question_Title": "Name Something That Tastes Better With Salt On It",
   "Answer_1": "French Fries",
   "Answer_1_Points": 23,
   "Answer_2": "Eggs",
   "Answer_2_Points": 16,
   "Answer_3": "Potato Chips",
   "Answer_3_Points": 9,
   "Answer_4": "Corn On The Cob",
   "Answer_4_Points": 8,
   "Answer_5": "Meat",
   "Answer_5_Points": 8,
   "Answer_6": "Tomatoes",
   "Answer_6_Points": 7
 },
 {
   "Question_ID": 117,
   "Question_Title": "Name A Reason You May Not Be Able To Get Home For The Holidays",
   "Answer_1": "Sick",
   "Answer_1_Points": 17,
   "Answer_2": "Work",
   "Answer_2_Points": 14,
   "Answer_3": "Broke",
   "Answer_3_Points": 12,
   "Answer_4": "Far Away",
   "Answer_4_Points": 4,
   "Answer_5": "Car Problems",
   "Answer_5_Points": 3,
   "Answer_6": "Too Much Homework",
   "Answer_6_Points": 2
 },
 {
   "Question_ID": 118,
   "Question_Title": "Name Something A Kid Might Use To Slide Down The Stairs",
   "Answer_1": "PILLOW",
   "Answer_1_Points": 29,
   "Answer_2": "CARDBOARD BOX",
   "Answer_2_Points": 22,
   "Answer_3": "BLANKET",
   "Answer_3_Points": 21,
   "Answer_4": "BEHIND",
   "Answer_4_Points": 8,
   "Answer_5": "MATTRESS",
   "Answer_5_Points": 8,
   "Answer_6": "TOWEL",
   "Answer_6_Points": 8
 },
 {
   "Question_ID": 119,
   "Question_Title": "Name Something Many people Buy With Credit Card Instead Of Cash",
   "Answer_1": "Clothes",
   "Answer_1_Points": 30,
   "Answer_2": "Car",
   "Answer_2_Points": 22,
   "Answer_3": "Gas",
   "Answer_3_Points": 18,
   "Answer_4": "Food",
   "Answer_4_Points": 16,
   "Answer_5": "Furniture",
   "Answer_5_Points": 7,
   "Answer_6": "TV",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 120,
   "Question_Title": "Name A Food That Some People Prefer To Eat Burnt",
   "Answer_1": "Toast",
   "Answer_1_Points": 39,
   "Answer_2": "Marshmellow",
   "Answer_2_Points": 18,
   "Answer_3": "Popcorn",
   "Answer_3_Points": 13,
   "Answer_4": "Steak",
   "Answer_4_Points": 11,
   "Answer_5": "Bacon",
   "Answer_5_Points": 10,
   "Answer_6": "Hot Dogs",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 121,
   "Question_Title": "Name An Activity People Commonly Take Up After Retirement.",
   "Answer_1": "Golf",
   "Answer_1_Points": 47,
   "Answer_2": "Gardening",
   "Answer_2_Points": 17,
   "Answer_3": "Traveling",
   "Answer_3_Points": 16,
   "Answer_4": "Fishing",
   "Answer_4_Points": 10,
   "Answer_5": "Playing An Instrument",
   "Answer_5_Points": 3,
   "Answer_6": "Knitting",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 122,
   "Question_Title": "At A party where You Don’t Know Anyone, How Might You Pass The Time?",
   "Answer_1": "Drink",
   "Answer_1_Points": 42,
   "Answer_2": "Dance",
   "Answer_2_Points": 22,
   "Answer_3": "Eat",
   "Answer_3_Points": 20,
   "Answer_4": "WatchTV",
   "Answer_4_Points": 7,
   "Answer_5": "Introduce Yourself",
   "Answer_5_Points": 3,
   "Answer_6": "Listen To Music",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 123,
   "Question_Title": "Name Something That Both A Dental Office And A Spa Might Have",
   "Answer_1": "Chair",
   "Answer_1_Points": 29,
   "Answer_2": "Water",
   "Answer_2_Points": 29,
   "Answer_3": "Magazines",
   "Answer_3_Points": 14,
   "Answer_4": "Towels",
   "Answer_4_Points": 9,
   "Answer_5": "Waiting Room",
   "Answer_5_Points": 9,
   "Answer_6": "Music",
   "Answer_6_Points": 8
 },
 {
   "Question_ID": 125,
   "Question_Title": "Name Something A Hotel Guest Calls The Front Desk To Ask About",
   "Answer_1": "Room Service",
   "Answer_1_Points": 32,
   "Answer_2": "Getting More Towels",
   "Answer_2_Points": 26,
   "Answer_3": "Wake Up Call",
   "Answer_3_Points": 23,
   "Answer_4": "Check Out Time",
   "Answer_4_Points": 9,
   "Answer_5": "Noise",
   "Answer_5_Points": 4,
   "Answer_6": "Phone Message",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 126,
   "Question_Title": "Name Something That May Be Found Washed Up On The Beach",
   "Answer_1": "Sea shells",
   "Answer_1_Points": 18,
   "Answer_2": "Seaweed",
   "Answer_2_Points": 18,
   "Answer_3": "Bottle",
   "Answer_3_Points": 14,
   "Answer_4": "Whale",
   "Answer_4_Points": 12,
   "Answer_5": "Garbage",
   "Answer_5_Points": 8,
   "Answer_6": "Shoes",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 128,
   "Question_Title": "Name Something That A Very thrifty Person Would Re-Use after A Birthday Party",
   "Answer_1": "Candles",
   "Answer_1_Points": 48,
   "Answer_2": "Wrapping paper",
   "Answer_2_Points": 26,
   "Answer_3": "Paper Plates",
   "Answer_3_Points": 9,
   "Answer_4": "Plastic Cups",
   "Answer_4_Points": 6,
   "Answer_5": "Decorations",
   "Answer_5_Points": 4,
   "Answer_6": "Tablecloth/Napkins",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 129,
   "Question_Title": "Name Something You’ll Find On The Breakfast Menu No Matter What Kind Of Restaurant You’re At",
   "Answer_1": "Eggs",
   "Answer_1_Points": 35,
   "Answer_2": "Coffee",
   "Answer_2_Points": 30,
   "Answer_3": "Pancakes",
   "Answer_3_Points": 16,
   "Answer_4": "Bacon",
   "Answer_4_Points": 6,
   "Answer_5": "Juice",
   "Answer_5_Points": 4,
   "Answer_6": "Toast",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 130,
   "Question_Title": "Name A Gift That’s great To Give To Children If You Don’t Live With Them.",
   "Answer_1": "Drum",
   "Answer_1_Points": 30,
   "Answer_2": "Candy",
   "Answer_2_Points": 22,
   "Answer_3": "Dog",
   "Answer_3_Points": 16,
   "Answer_4": "Horn",
   "Answer_4_Points": 12,
   "Answer_5": "Guitar",
   "Answer_5_Points": 10,
   "Answer_6": "Toy Gun",
   "Answer_6_Points": 7
 },
 {
   "Question_ID": 132,
   "Question_Title": "name a Profession Where You Might Be Fired If You Lost Your Voice",
   "Answer_1": "Singer",
   "Answer_1_Points": 52,
   "Answer_2": "Radio Host",
   "Answer_2_Points": 15,
   "Answer_3": "Teacher",
   "Answer_3_Points": 10,
   "Answer_4": "Receptionist",
   "Answer_4_Points": 8,
   "Answer_5": "Telemarketer",
   "Answer_5_Points": 5,
   "Answer_6": "Actor",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 133,
   "Question_Title": "Name Something You shouldn’t Squeeze too Tightly",
   "Answer_1": "Baby",
   "Answer_1_Points": 12,
   "Answer_2": "Vegetables",
   "Answer_2_Points": 11,
   "Answer_3": "Eggs",
   "Answer_3_Points": 8,
   "Answer_4": "Balloon",
   "Answer_4_Points": 7,
   "Answer_5": "Charmin Tissue",
   "Answer_5_Points": 6,
   "Answer_6": "Bread",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 134,
   "Question_Title": "Name The Part Of The Wedding That The Bride And Groom Might Do More Out Of Tradition Than Choice",
   "Answer_1": "Vows",
   "Answer_1_Points": 36,
   "Answer_2": "Kiss On Command",
   "Answer_2_Points": 23,
   "Answer_3": "Dance",
   "Answer_3_Points": 17,
   "Answer_4": "Cut The Cake",
   "Answer_4_Points": 10,
   "Answer_5": "Throw Bouqueu",
   "Answer_5_Points": 6,
   "Answer_6": "Bridal Song",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 135,
   "Question_Title": "Name Something You See Or Hear That Reminds You Of An Ex.",
   "Answer_1": "Song",
   "Answer_1_Points": 61,
   "Answer_2": "Voice",
   "Answer_2_Points": 13,
   "Answer_3": "Photo",
   "Answer_3_Points": 9,
   "Answer_4": "Movie",
   "Answer_4_Points": 6,
   "Answer_5": "Name",
   "Answer_5_Points": 5,
   "Answer_6": "Car",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 136,
   "Question_Title": "Name Something Made with Ginger",
   "Answer_1": "Cookies",
   "Answer_1_Points": 58,
   "Answer_2": "Ginger Ale",
   "Answer_2_Points": 12,
   "Answer_3": "Pumpkin Pie",
   "Answer_3_Points": 10,
   "Answer_4": "Tea",
   "Answer_4_Points": 7,
   "Answer_5": "Ginger chicken",
   "Answer_5_Points": 6,
   "Answer_6": "Carrot Cake",
   "Answer_6_Points": 2
 },
 {
   "Question_ID": 137,
   "Question_Title": "Name Something A Person With Extra Long Arms Would Be Good At",
   "Answer_1": "Sports",
   "Answer_1_Points": 51,
   "Answer_2": "Reaching",
   "Answer_2_Points": 26,
   "Answer_3": "Hugging",
   "Answer_3_Points": 6,
   "Answer_4": "Rock Climbing",
   "Answer_4_Points": 6,
   "Answer_5": "Paint Ceilings",
   "Answer_5_Points": 5,
   "Answer_6": "Change Lightbulbs",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 138,
   "Question_Title": "Name Something A Kid Would Do After School To Make An Extra Buck",
   "Answer_1": "Mow Lawns",
   "Answer_1_Points": 49,
   "Answer_2": "Babysit",
   "Answer_2_Points": 17,
   "Answer_3": "Paper Route",
   "Answer_3_Points": 10,
   "Answer_4": "Sell Lemonade",
   "Answer_4_Points": 8,
   "Answer_5": "Wash Cars",
   "Answer_5_Points": 8,
   "Answer_6": "Chores",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 140,
   "Question_Title": "Complete This Sentence. I’d Never Date Someone Who had bad ___________ .",
   "Answer_1": "Breath",
   "Answer_1_Points": 42,
   "Answer_2": "Hair",
   "Answer_2_Points": 27,
   "Answer_3": "manners",
   "Answer_3_Points": 12,
   "Answer_4": "Attitude",
   "Answer_4_Points": 8,
   "Answer_5": "Hygiene",
   "Answer_5_Points": 5,
   "Answer_6": "Credit",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 141,
   "Question_Title": "Name Someone The Groom Might Not Want At His Bachelor Party",
   "Answer_1": "Bride",
   "Answer_1_Points": 35,
   "Answer_2": "Ex",
   "Answer_2_Points": 20,
   "Answer_3": "Dancer",
   "Answer_3_Points": 16,
   "Answer_4": "Mom",
   "Answer_4_Points": 13,
   "Answer_5": "Dad",
   "Answer_5_Points": 7,
   "Answer_6": "Father N Law",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 142,
   "Question_Title": "Name Something You’d Like to Have In Your Backyard",
   "Answer_1": "Pool",
   "Answer_1_Points": 61,
   "Answer_2": "Garden",
   "Answer_2_Points": 12,
   "Answer_3": "Swingset",
   "Answer_3_Points": 9,
   "Answer_4": "Grill",
   "Answer_4_Points": 6,
   "Answer_5": "Fence",
   "Answer_5_Points": 4,
   "Answer_6": "Fountain",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 143,
   "Question_Title": "Tell Me Something You Only Do When You’re Sick.",
   "Answer_1": "Nap",
   "Answer_1_Points": 37,
   "Answer_2": "Vomit",
   "Answer_2_Points": 34,
   "Answer_3": "Take Medicine",
   "Answer_3_Points": 14,
   "Answer_4": "Eat Soup",
   "Answer_4_Points": 8,
   "Answer_5": "Home From Work",
   "Answer_5_Points": 3,
   "Answer_6": "Go To Doctor",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 145,
   "Question_Title": "Name Something That Probably Drops In Sales In The Winter.",
   "Answer_1": "Swimsuit",
   "Answer_1_Points": 35,
   "Answer_2": "Summer Clothing",
   "Answer_2_Points": 18,
   "Answer_3": "Pool Equipment",
   "Answer_3_Points": 16,
   "Answer_4": "Lawn Care",
   "Answer_4_Points": 13,
   "Answer_5": "Ice Cream",
   "Answer_5_Points": 6,
   "Answer_6": "Air Conditioner",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 147,
   "Question_Title": "Name Something A Husband Might Forget To Take To The Hospital When His Wife Is Having A Baby.",
   "Answer_1": "Suitcase",
   "Answer_1_Points": 43,
   "Answer_2": "Wife",
   "Answer_2_Points": 19,
   "Answer_3": "Extra Clothes",
   "Answer_3_Points": 18,
   "Answer_4": "Baby Bag",
   "Answer_4_Points": 5,
   "Answer_5": "Flowers",
   "Answer_5_Points": 4,
   "Answer_6": "Car Seat",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 148,
   "Question_Title": "Name An Occupation In Which One Spends His Day Cutting.",
   "Answer_1": "Barber",
   "Answer_1_Points": 41,
   "Answer_2": "Butcher",
   "Answer_2_Points": 26,
   "Answer_3": "Gardener",
   "Answer_3_Points": 13,
   "Answer_4": "Tailor",
   "Answer_4_Points": 9,
   "Answer_5": "Lumberjack",
   "Answer_5_Points": 5,
   "Answer_6": "Carpenter",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 149,
   "Question_Title": "When You’re Stressed Out, Name The Part Of Your Body Where You Feel It Most.",
   "Answer_1": "Head",
   "Answer_1_Points": 40,
   "Answer_2": "Neck",
   "Answer_2_Points": 23,
   "Answer_3": "Back",
   "Answer_3_Points": 18,
   "Answer_4": "Shoulders",
   "Answer_4_Points": 10,
   "Answer_5": "Feet",
   "Answer_5_Points": 2,
   "Answer_6": "Chest",
   "Answer_6_Points": 2
 },
 {
   "Question_ID": 150,
   "Question_Title": "Name Someone, Real Or Fictional, Who Is Known For Having A White Beard.",
   "Answer_1": "Santa Claus",
   "Answer_1_Points": 37,
   "Answer_2": "Moses",
   "Answer_2_Points": 22,
   "Answer_3": "Uncle Sam",
   "Answer_3_Points": 20,
   "Answer_4": "Kenny Rogers",
   "Answer_4_Points": 7,
   "Answer_5": "Merlin/Wizard",
   "Answer_5_Points": 7,
   "Answer_6": "Colonel Sanders",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 151,
   "Question_Title": "Name Something You’d Be Surprised To Hear A Six Month Old Baby Has Already Learned How To Do.",
   "Answer_1": "Walk",
   "Answer_1_Points": 58,
   "Answer_2": "Talk",
   "Answer_2_Points": 20,
   "Answer_3": "Read",
   "Answer_3_Points": 6,
   "Answer_4": "Eat On Their Own",
   "Answer_4_Points": 5,
   "Answer_5": "Hold A Bottle",
   "Answer_5_Points": 4,
   "Answer_6": "Crawl",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 152,
   "Question_Title": "Name Something Babies And Puppies Have In Common.",
   "Answer_1": "Cute",
   "Answer_1_Points": 34,
   "Answer_2": "Drooling",
   "Answer_2_Points": 17,
   "Answer_3": "Need Attention",
   "Answer_3_Points": 13,
   "Answer_4": "Playful",
   "Answer_4_Points": 9,
   "Answer_5": "Sleep Alot",
   "Answer_5_Points": 8,
   "Answer_6": "Cry",
   "Answer_6_Points": 8
 },
 {
   "Question_ID": 153,
   "Question_Title": "Name An Animal That Travels In Groups.",
   "Answer_1": "Birds",
   "Answer_1_Points": 37,
   "Answer_2": "Wolves",
   "Answer_2_Points": 19,
   "Answer_3": "Fish",
   "Answer_3_Points": 17,
   "Answer_4": "Lions",
   "Answer_4_Points": 12,
   "Answer_5": "Elephant",
   "Answer_5_Points": 9,
   "Answer_6": "Deer",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 154,
   "Question_Title": "Name Something People Might Do With A Rental Car That They Wouldn’t Do With Their Own Car.",
   "Answer_1": "Speed",
   "Answer_1_Points": 40,
   "Answer_2": "Not Clean It",
   "Answer_2_Points": 15,
   "Answer_3": "Travel Far",
   "Answer_3_Points": 13,
   "Answer_4": "Smoke In It",
   "Answer_4_Points": 9,
   "Answer_5": "Crash It",
   "Answer_5_Points": 7,
   "Answer_6": "Drive Recklessly",
   "Answer_6_Points": 7
 },
 {
   "Question_ID": 155,
   "Question_Title": "Name The Job You Wouldn’t Want To Have If You Worked At The Circus",
   "Answer_1": "Janitor",
   "Answer_1_Points": 55,
   "Answer_2": "Clown",
   "Answer_2_Points": 13,
   "Answer_3": "Lion Tamer",
   "Answer_3_Points": 12,
   "Answer_4": "Human Cannon Ball",
   "Answer_4_Points": 6,
   "Answer_5": "Tight Rope Walker",
   "Answer_5_Points": 4,
   "Answer_6": "Elephant Trainer",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 156,
   "Question_Title": "Name Something Parents Say Is Too Short.",
   "Answer_1": "Childhood",
   "Answer_1_Points": 29,
   "Answer_2": "Daughter’s Skirt",
   "Answer_2_Points": 28,
   "Answer_3": "Summer/School Calendar",
   "Answer_3_Points": 17,
   "Answer_4": "Money",
   "Answer_4_Points": 11,
   "Answer_5": "Life",
   "Answer_5_Points": 10,
   "Answer_6": "Fuse/Temper",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 157,
   "Question_Title": "Name A Part of A Fish That Most People Don’t Eat.",
   "Answer_1": "Head",
   "Answer_1_Points": 33,
   "Answer_2": "Eyes",
   "Answer_2_Points": 27,
   "Answer_3": "Tail/Fin",
   "Answer_3_Points": 19,
   "Answer_4": "Bones",
   "Answer_4_Points": 14,
   "Answer_5": "Scales",
   "Answer_5_Points": 3,
   "Answer_6": "Giills",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 160,
   "Question_Title": "At An Awards Show, Name Something Celebs Might Be Doing When The Camera Pans On Them.",
   "Answer_1": "Smiling",
   "Answer_1_Points": 62,
   "Answer_2": "Waving",
   "Answer_2_Points": 11,
   "Answer_3": "Posing",
   "Answer_3_Points": 10,
   "Answer_4": "Crying",
   "Answer_4_Points": 5,
   "Answer_5": "Clapping",
   "Answer_5_Points": 3,
   "Answer_6": "Kissing Date",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 161,
   "Question_Title": "Name Something That Might Happen As Bad Luck On Your Honeymoon.",
   "Answer_1": "Break Up",
   "Answer_1_Points": 38,
   "Answer_2": "Bad Weather",
   "Answer_2_Points": 33,
   "Answer_3": "Don’t Get Along",
   "Answer_3_Points": 7,
   "Answer_4": "Miss Flight",
   "Answer_4_Points": 6,
   "Answer_5": "Get Sick",
   "Answer_5_Points": 6,
   "Answer_6": "Lose Luggage",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 163,
   "Question_Title": "To Feel Safer At Night, Name Something You Would Go To Sleep With.",
   "Answer_1": "Weapon",
   "Answer_1_Points": 47,
   "Answer_2": "Teddy Bear",
   "Answer_2_Points": 23,
   "Answer_3": "Bat",
   "Answer_3_Points": 8,
   "Answer_4": "Dog",
   "Answer_4_Points": 8,
   "Answer_5": "Night Light",
   "Answer_5_Points": 6,
   "Answer_6": "Partner",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 164,
   "Question_Title": "Name A Computer Program Or Skill That You Wish You Were Better At.",
   "Answer_1": "Typing",
   "Answer_1_Points": 63,
   "Answer_2": "Excel",
   "Answer_2_Points": 11,
   "Answer_3": "Word Processor",
   "Answer_3_Points": 8,
   "Answer_4": "Surfing The Net",
   "Answer_4_Points": 6,
   "Answer_5": "Programming",
   "Answer_5_Points": 4,
   "Answer_6": "Power Point",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 167,
   "Question_Title": "Name Something Parents Photograph Their Baby Doing For The First Time.",
   "Answer_1": "Walking",
   "Answer_1_Points": 37,
   "Answer_2": "Smiling",
   "Answer_2_Points": 20,
   "Answer_3": "Eating",
   "Answer_3_Points": 18,
   "Answer_4": "Taking A Bath",
   "Answer_4_Points": 10,
   "Answer_5": "Crawling",
   "Answer_5_Points": 8,
   "Answer_6": "Sleeping",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 168,
   "Question_Title": "Name A Winter Activity That Makes You Sweat.",
   "Answer_1": "Skiing",
   "Answer_1_Points": 29,
   "Answer_2": "Ice Skating/Hockey",
   "Answer_2_Points": 16,
   "Answer_3": "Snowboarding",
   "Answer_3_Points": 15,
   "Answer_4": "Shoveling",
   "Answer_4_Points": 14,
   "Answer_5": "Sledding",
   "Answer_5_Points": 14,
   "Answer_6": "Snowball Fight",
   "Answer_6_Points": 8
 },
 {
   "Question_ID": 173,
   "Question_Title": "Name The Vegetable That Tastes The Worst When it Comes From A Can.",
   "Answer_1": "Peas",
   "Answer_1_Points": 35,
   "Answer_2": "Spinach",
   "Answer_2_Points": 22,
   "Answer_3": "Carrots",
   "Answer_3_Points": 17,
   "Answer_4": "Corn",
   "Answer_4_Points": 11,
   "Answer_5": "Green Beans",
   "Answer_5_Points": 7,
   "Answer_6": "Asparagus",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 176,
   "Question_Title": "Name A Job That A Clumsy Person Would Be Fired From Immediately.",
   "Answer_1": "Food Server",
   "Answer_1_Points": 35,
   "Answer_2": "Surgeon",
   "Answer_2_Points": 28,
   "Answer_3": "Construction Worker",
   "Answer_3_Points": 10,
   "Answer_4": "Dancer",
   "Answer_4_Points": 6,
   "Answer_5": "Acrobat",
   "Answer_5_Points": 5,
   "Answer_6": "Bartender",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 177,
   "Question_Title": "While Looking For A New Home, What Would You Be Surprised To Find That A House Didn’t Have?",
   "Answer_1": "Bathroom",
   "Answer_1_Points": 51,
   "Answer_2": "Kitchen",
   "Answer_2_Points": 15,
   "Answer_3": "Roof",
   "Answer_3_Points": 10,
   "Answer_4": "Garage",
   "Answer_4_Points": 9,
   "Answer_5": "Doors",
   "Answer_5_Points": 5,
   "Answer_6": "Basement",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 178,
   "Question_Title": "Name Something You Expect To See In A Martial Arts Movie.",
   "Answer_1": "Fight Scenes",
   "Answer_1_Points": 43,
   "Answer_2": "Asian Actors",
   "Answer_2_Points": 20,
   "Answer_3": "Weapons",
   "Answer_3_Points": 14,
   "Answer_4": "Subtitles/Dubbing",
   "Answer_4_Points": 9,
   "Answer_5": "Ninjas",
   "Answer_5_Points": 7,
   "Answer_6": "Blood",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 179,
   "Question_Title": "Name Something That Would Keep You From Snuggling Up To Your Spouse In Bed.",
   "Answer_1": "Sick",
   "Answer_1_Points": 25,
   "Answer_2": "Snoring",
   "Answer_2_Points": 20,
   "Answer_3": "Bad Breath",
   "Answer_3_Points": 22,
   "Answer_4": "Gas",
   "Answer_4_Points": 13,
   "Answer_5": "Cold Feet",
   "Answer_5_Points": 12,
   "Answer_6": "Body Odor",
   "Answer_6_Points": 8
 },
 {
   "Question_ID": 180,
   "Question_Title": "Name Another Word For “Courage.”",
   "Answer_1": "Brave",
   "Answer_1_Points": 70,
   "Answer_2": "Strength",
   "Answer_2_Points": 7,
   "Answer_3": "Fortitude",
   "Answer_3_Points": 6,
   "Answer_4": "Heroic",
   "Answer_4_Points": 4,
   "Answer_5": "Heart",
   "Answer_5_Points": 4,
   "Answer_6": "Bold",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 181,
   "Question_Title": "Name A Reason Why You Might Not Participate In Take-Your-Child-To-Work Day.",
   "Answer_1": "No Kids",
   "Answer_1_Points": 39,
   "Answer_2": "Job’s Not Suitable",
   "Answer_2_Points": 18,
   "Answer_3": "No Job",
   "Answer_3_Points": 18,
   "Answer_4": "Naughty Kid",
   "Answer_4_Points": 11,
   "Answer_5": "Too Busy At Work",
   "Answer_5_Points": 7,
   "Answer_6": "Boring Job",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 182,
   "Question_Title": "Tell Me Something You Hate To Discover That You’re Missing A Piece From.",
   "Answer_1": "Puzzle",
   "Answer_1_Points": 57,
   "Answer_2": "Earring",
   "Answer_2_Points": 15,
   "Answer_3": "Car",
   "Answer_3_Points": 10,
   "Answer_4": "Board Game",
   "Answer_4_Points": 6,
   "Answer_5": "Pie",
   "Answer_5_Points": 5,
   "Answer_6": "Cake",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 183,
   "Question_Title": "Name Something That Might Be Ruined If It Had A Scratch On It.",
   "Answer_1": "CD/Record",
   "Answer_1_Points": 44,
   "Answer_2": "Furniture",
   "Answer_2_Points": 16,
   "Answer_3": "Glasses/Eyeglasses",
   "Answer_3_Points": 11,
   "Answer_4": "Car",
   "Answer_4_Points": 11,
   "Answer_5": "Mirror",
   "Answer_5_Points": 6,
   "Answer_6": "Camera Lense",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 184,
   "Question_Title": "Name Something Sister Borrow From Their Brothers.",
   "Answer_1": "Clothes/Shoes",
   "Answer_1_Points": 54,
   "Answer_2": "Money",
   "Answer_2_Points": 21,
   "Answer_3": "Music/CDS",
   "Answer_3_Points": 7,
   "Answer_4": "Car",
   "Answer_4_Points": 6,
   "Answer_5": "Deoderant",
   "Answer_5_Points": 4,
   "Answer_6": "Comb/Brush",
   "Answer_6_Points": 2
 },
 {
   "Question_ID": 185,
   "Question_Title": "Name Something You’d Expect To See In A Boardroom Meeting.",
   "Answer_1": "Conference Table",
   "Answer_1_Points": 29,
   "Answer_2": "Executives",
   "Answer_2_Points": 26,
   "Answer_3": "Office Chairs",
   "Answer_3_Points": 17,
   "Answer_4": "Charts/Presentation",
   "Answer_4_Points": 12,
   "Answer_5": "Coffee/Donuts",
   "Answer_5_Points": 9,
   "Answer_6": "Computers/Phones",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 186,
   "Question_Title": "Name A Word That Begins With “Con.”",
   "Answer_1": "Convict",
   "Answer_1_Points": 24,
   "Answer_2": "Con Artist/Con Man",
   "Answer_2_Points": 22,
   "Answer_3": "Contest",
   "Answer_3_Points": 16,
   "Answer_4": "Contract",
   "Answer_4_Points": 13,
   "Answer_5": "Construction",
   "Answer_5_Points": 7,
   "Answer_6": "Connect",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 187,
   "Question_Title": "Name A Breed Of Dog That Everyone Has Heard Of.",
   "Answer_1": "Poodle",
   "Answer_1_Points": 31,
   "Answer_2": "Pit Bull",
   "Answer_2_Points": 21,
   "Answer_3": "German Shepherd",
   "Answer_3_Points": 15,
   "Answer_4": "Labrador",
   "Answer_4_Points": 12,
   "Answer_5": "Collie",
   "Answer_5_Points": 10,
   "Answer_6": "Dalmation",
   "Answer_6_Points": 8
 },
 {
   "Question_ID": 188,
   "Question_Title": "We Asked 100 Married People: Name The Thing That Your Spouse Most Often Complains About.",
   "Answer_1": "Money",
   "Answer_1_Points": 49,
   "Answer_2": "Lack Of Intimacy",
   "Answer_2_Points": 20,
   "Answer_3": "Dinner",
   "Answer_3_Points": 8,
   "Answer_4": "Snoring",
   "Answer_4_Points": 8,
   "Answer_5": "Work",
   "Answer_5_Points": 7,
   "Answer_6": "Doing Housework",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 189,
   "Question_Title": "Besides Coughing, What’s Something You Can’t Stop Yourself From Doing?",
   "Answer_1": "Sneezing",
   "Answer_1_Points": 52,
   "Answer_2": "Getting Hiccups",
   "Answer_2_Points": 11,
   "Answer_3": "Breathing",
   "Answer_3_Points": 11,
   "Answer_4": "Blinking",
   "Answer_4_Points": 7,
   "Answer_5": "Laughing",
   "Answer_5_Points": 6,
   "Answer_6": "Eating/Drinking",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 191,
   "Question_Title": "Name A Place Where It’s Usually Not OK To Wear Jeans.",
   "Answer_1": "Place Of Worship",
   "Answer_1_Points": 45,
   "Answer_2": "Work",
   "Answer_2_Points": 20,
   "Answer_3": "Wedding",
   "Answer_3_Points": 14,
   "Answer_4": "Beach/Pool",
   "Answer_4_Points": 7,
   "Answer_5": "Funeral",
   "Answer_5_Points": 4,
   "Answer_6": "Fine Restaurant",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 192,
   "Question_Title": "Name An Activity You Wouldn’t Want To Do In The Rain",
   "Answer_1": "Walk",
   "Answer_1_Points": 35,
   "Answer_2": "Picnic",
   "Answer_2_Points": 23,
   "Answer_3": "Golf",
   "Answer_3_Points": 16,
   "Answer_4": "Baseball",
   "Answer_4_Points": 14,
   "Answer_5": "Drive",
   "Answer_5_Points": 7,
   "Answer_6": "Garden",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 193,
   "Question_Title": "Name Something Teenagers Do That They’ll Kick Themselves For Later In Life.",
   "Answer_1": "Drink/Smoke",
   "Answer_1_Points": 28,
   "Answer_2": "Bad Grades",
   "Answer_2_Points": 20,
   "Answer_3": "Put Off College",
   "Answer_3_Points": 14,
   "Answer_4": "Drop Out",
   "Answer_4_Points": 14,
   "Answer_5": "Date Too Soon",
   "Answer_5_Points": 12,
   "Answer_6": "Get A Tattoo",
   "Answer_6_Points": 9
 },
 {
   "Question_ID": 194,
   "Question_Title": "Name Something That Could Ruin A Romantic Dinner.",
   "Answer_1": "Passing Gas",
   "Answer_1_Points": 21,
   "Answer_2": "Fight",
   "Answer_2_Points": 19,
   "Answer_3": "Bad Food",
   "Answer_3_Points": 18,
   "Answer_4": "Phone Call",
   "Answer_4_Points": 16,
   "Answer_5": "Kids",
   "Answer_5_Points": 15,
   "Answer_6": "Getting Sick",
   "Answer_6_Points": 9
 },
 {
   "Question_ID": 198,
   "Question_Title": "Name A Good Place To Spend The Day When It’s Raining Outside.",
   "Answer_1": "Home",
   "Answer_1_Points": 37,
   "Answer_2": "Movie Theatre",
   "Answer_2_Points": 28,
   "Answer_3": "Mall",
   "Answer_3_Points": 17,
   "Answer_4": "Library",
   "Answer_4_Points": 11,
   "Answer_5": "Museum",
   "Answer_5_Points": 3,
   "Answer_6": "Gym",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 199,
   "Question_Title": "Name Something You Do At Least Twice In The Course Of A Long Car Ride With Family.",
   "Answer_1": "Sing",
   "Answer_1_Points": 27,
   "Answer_2": "Fall Asleep",
   "Answer_2_Points": 26,
   "Answer_3": "Make A Pit Stop",
   "Answer_3_Points": 22,
   "Answer_4": "Get Food",
   "Answer_4_Points": 14,
   "Answer_5": "Fight",
   "Answer_5_Points": 5,
   "Answer_6": "Hear Are We There Yet",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 200,
   "Question_Title": "Name A Way People Try To Stop A Bloody Nose.",
   "Answer_1": "Hold Head Back",
   "Answer_1_Points": 51,
   "Answer_2": "Pinch Nose",
   "Answer_2_Points": 31,
   "Answer_3": "With A Tissue",
   "Answer_3_Points": 6,
   "Answer_4": "Cotton In Nose",
   "Answer_4_Points": 4,
   "Answer_5": "Cold Towel",
   "Answer_5_Points": 4,
   "Answer_6": "Ice",
   "Answer_6_Points": 2
 },
 {
   "Question_ID": 202,
   "Question_Title": "Name A Reason Why It’s Harder To Get Out Of Bed On Some Days Than On Others.",
   "Answer_1": "Tired",
   "Answer_1_Points": 37,
   "Answer_2": "Sick",
   "Answer_2_Points": 27,
   "Answer_3": "Bad Weather",
   "Answer_3_Points": 17,
   "Answer_4": "Going To Work/School",
   "Answer_4_Points": 12,
   "Answer_5": "Stayed Up Late",
   "Answer_5_Points": 3,
   "Answer_6": "It’s Monday",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 204,
   "Question_Title": "Besides Utensils, Name Something That’s Already On The Restaurant Table When You Sit Down.",
   "Answer_1": "Napkins",
   "Answer_1_Points": 46,
   "Answer_2": "Salt And Pepper",
   "Answer_2_Points": 19,
   "Answer_3": "Menu",
   "Answer_3_Points": 11,
   "Answer_4": "Glass",
   "Answer_4_Points": 8,
   "Answer_5": "Table Cloth",
   "Answer_5_Points": 5,
   "Answer_6": "Ketchup",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 205,
   "Question_Title": "Name Something You’d See On The Back Of A Car.",
   "Answer_1": "License Plate",
   "Answer_1_Points": 32,
   "Answer_2": "Bumper Stickers",
   "Answer_2_Points": 31,
   "Answer_3": "Bumper",
   "Answer_3_Points": 17,
   "Answer_4": "Dirt",
   "Answer_4_Points": 5,
   "Answer_5": "Tires",
   "Answer_5_Points": 4,
   "Answer_6": "Lights",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 208,
   "Question_Title": "Name Something Rude People Do While You’re Trying To Talk To Them On The Phone.",
   "Answer_1": "Talk To Someone Else",
   "Answer_1_Points": 27,
   "Answer_2": "Eat",
   "Answer_2_Points": 21,
   "Answer_3": "Interrupt",
   "Answer_3_Points": 21,
   "Answer_4": "Hang Up",
   "Answer_4_Points": 11,
   "Answer_5": "Put You On Hold",
   "Answer_5_Points": 8,
   "Answer_6": "make Noises",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 209,
   "Question_Title": "Tell Me A Creature That You’d Hate To Hear In Your Room At Night.",
   "Answer_1": "Rodent",
   "Answer_1_Points": 39,
   "Answer_2": "Cricket",
   "Answer_2_Points": 18,
   "Answer_3": "Snake",
   "Answer_3_Points": 15,
   "Answer_4": "Monster",
   "Answer_4_Points": 14,
   "Answer_5": "Fly",
   "Answer_5_Points": 4,
   "Answer_6": "Mosquito",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 210,
   "Question_Title": "For Which Occasion Would You Hate To Forget To Buy A Gift?",
   "Answer_1": "Birthday",
   "Answer_1_Points": 31,
   "Answer_2": "Anniversary",
   "Answer_2_Points": 20,
   "Answer_3": "Wedding",
   "Answer_3_Points": 19,
   "Answer_4": "Christmas",
   "Answer_4_Points": 17,
   "Answer_5": "Valentines Day",
   "Answer_5_Points": 5,
   "Answer_6": "Mothers Day",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 211,
   "Question_Title": "Name Something Besides Food And Drinks That You Can Buy At Starbucks.",
   "Answer_1": "Mugs",
   "Answer_1_Points": 45,
   "Answer_2": "Reading Material",
   "Answer_2_Points": 32,
   "Answer_3": "Gift Cards",
   "Answer_3_Points": 8,
   "Answer_4": "T Shirt",
   "Answer_4_Points": 3,
   "Answer_5": "Coffee Maker",
   "Answer_5_Points": 3,
   "Answer_6": "Music",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 212,
   "Question_Title": "Name A Punishment That A Misbehaving Kid Might Get At School.",
   "Answer_1": "Detention",
   "Answer_1_Points": 51,
   "Answer_2": "Stand In Corner",
   "Answer_2_Points": 26,
   "Answer_3": "Suspension",
   "Answer_3_Points": 9,
   "Answer_4": "Write Lines",
   "Answer_4_Points": 6,
   "Answer_5": "Principal’s Office",
   "Answer_5_Points": 4,
   "Answer_6": "No Recess",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 213,
   "Question_Title": "Name A Reason Why A Child Can’t Wait To Grow Up",
   "Answer_1": "Drive",
   "Answer_1_Points": 35,
   "Answer_2": "Move Out",
   "Answer_2_Points": 22,
   "Answer_3": "Have A Job",
   "Answer_3_Points": 14,
   "Answer_4": "No Rules",
   "Answer_4_Points": 12,
   "Answer_5": "Romance",
   "Answer_5_Points": 7,
   "Answer_6": "No School",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 214,
   "Question_Title": "Name Something That Kids Can Use In A Pool To Help Them Float.",
   "Answer_1": "Raft",
   "Answer_1_Points": 32,
   "Answer_2": "Inner Tube",
   "Answer_2_Points": 19,
   "Answer_3": "Beach Ball",
   "Answer_3_Points": 14,
   "Answer_4": "Life Jacket",
   "Answer_4_Points": 14,
   "Answer_5": "Water Wings",
   "Answer_5_Points": 12,
   "Answer_6": "Noodle",
   "Answer_6_Points": 7
 },
 {
   "Question_ID": 215,
   "Question_Title": "Name Something That Grows On Trees, But Isn’t Fruit.",
   "Answer_1": "Leaves",
   "Answer_1_Points": 49,
   "Answer_2": "Nuts",
   "Answer_2_Points": 25,
   "Answer_3": "Flowers",
   "Answer_3_Points": 10,
   "Answer_4": "Acorn",
   "Answer_4_Points": 8,
   "Answer_5": "Money",
   "Answer_5_Points": 4,
   "Answer_6": "Pine Cones",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 216,
   "Question_Title": "Name Something You Need In Order To Make A Garden.",
   "Answer_1": "Seeds",
   "Answer_1_Points": 35,
   "Answer_2": "Soil",
   "Answer_2_Points": 28,
   "Answer_3": "Water Cooler",
   "Answer_3_Points": 15,
   "Answer_4": "Hoe",
   "Answer_4_Points": 7,
   "Answer_5": "Shovel",
   "Answer_5_Points": 5,
   "Answer_6": "Plot Of Land",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 219,
   "Question_Title": "Name Something Adults Buy That Can Be Very Small Or Very Large.",
   "Answer_1": "TV",
   "Answer_1_Points": 36,
   "Answer_2": "Car/Vehicle",
   "Answer_2_Points": 29,
   "Answer_3": "House",
   "Answer_3_Points": 21,
   "Answer_4": "Oven",
   "Answer_4_Points": 5,
   "Answer_5": "Stereo/Speakers",
   "Answer_5_Points": 4,
   "Answer_6": "Refrigerator",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 220,
   "Question_Title": "Name A Subject You Count On Your Partner To Give You Advice On.",
   "Answer_1": "Money",
   "Answer_1_Points": 31,
   "Answer_2": "Work",
   "Answer_2_Points": 24,
   "Answer_3": "Romance",
   "Answer_3_Points": 24,
   "Answer_4": "Fashion",
   "Answer_4_Points": 7,
   "Answer_5": "Parenting",
   "Answer_5_Points": 5,
   "Answer_6": "Relationships",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 221,
   "Question_Title": "Name Something You Can Get From Your Parents, But You Can Change As An Adult.",
   "Answer_1": "Name",
   "Answer_1_Points": 49,
   "Answer_2": "Hair Color",
   "Answer_2_Points": 19,
   "Answer_3": "Economic Status",
   "Answer_3_Points": 13,
   "Answer_4": "Attitude",
   "Answer_4_Points": 7,
   "Answer_5": "Nose",
   "Answer_5_Points": 6,
   "Answer_6": "Religion",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 222,
   "Question_Title": "Name An Instrument That You’d Need To Be Really Coordinated To Play.",
   "Answer_1": "Piano",
   "Answer_1_Points": 39,
   "Answer_2": "Drums",
   "Answer_2_Points": 29,
   "Answer_3": "Guitar",
   "Answer_3_Points": 15,
   "Answer_4": "Violin",
   "Answer_4_Points": 5,
   "Answer_5": "Flute",
   "Answer_5_Points": 4,
   "Answer_6": "Saxophone",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 223,
   "Question_Title": "Besides “Biographies,” Which Section Of A Bookstore Would A Memoir About Your Life Belong In?",
   "Answer_1": "Humor/Comics",
   "Answer_1_Points": 31,
   "Answer_2": "Romance",
   "Answer_2_Points": 19,
   "Answer_3": "History",
   "Answer_3_Points": 17,
   "Answer_4": "Horror",
   "Answer_4_Points": 12,
   "Answer_5": "Self Help",
   "Answer_5_Points": 11,
   "Answer_6": "Sci Fi/Fantasy",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 224,
   "Question_Title": "At The Beach, Name Something That Might Protect You From Sun.",
   "Answer_1": "Umbrella",
   "Answer_1_Points": 38,
   "Answer_2": "Sunscreen",
   "Answer_2_Points": 36,
   "Answer_3": "Sun Hat",
   "Answer_3_Points": 14,
   "Answer_4": "Sunglasses",
   "Answer_4_Points": 5,
   "Answer_5": "Cover Up",
   "Answer_5_Points": 3,
   "Answer_6": "Shade",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 225,
   "Question_Title": "What Animal Would You See At A Farm, But Never Consider Keeping For A Pet?",
   "Answer_1": "Cow",
   "Answer_1_Points": 47,
   "Answer_2": "Pig",
   "Answer_2_Points": 34,
   "Answer_3": "Goat",
   "Answer_3_Points": 6,
   "Answer_4": "Chicken",
   "Answer_4_Points": 5,
   "Answer_5": "Horse",
   "Answer_5_Points": 3,
   "Answer_6": "Sheep",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 226,
   "Question_Title": "Name A Gift That Most Women Like To Get.",
   "Answer_1": "Jewlery",
   "Answer_1_Points": 48,
   "Answer_2": "Flowers",
   "Answer_2_Points": 17,
   "Answer_3": "Clothing",
   "Answer_3_Points": 10,
   "Answer_4": "Money",
   "Answer_4_Points": 8,
   "Answer_5": "Perfume",
   "Answer_5_Points": 6,
   "Answer_6": "Shoes",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 227,
   "Question_Title": "Name Something That’s Often Brought Into A Pawn Shop.",
   "Answer_1": "Jewelry",
   "Answer_1_Points": 36,
   "Answer_2": "TV",
   "Answer_2_Points": 24,
   "Answer_3": "Watch",
   "Answer_3_Points": 17,
   "Answer_4": "Gun",
   "Answer_4_Points": 11,
   "Answer_5": "Musical Instrument",
   "Answer_5_Points": 5,
   "Answer_6": "Stereo",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 230,
   "Question_Title": "Tell Me A Reason You Exit The Freeway.",
   "Answer_1": "Traffic Jam",
   "Answer_1_Points": 33,
   "Answer_2": "Get Gas",
   "Answer_2_Points": 27,
   "Answer_3": "Your Destination",
   "Answer_3_Points": 17,
   "Answer_4": "Accident",
   "Answer_4_Points": 9,
   "Answer_5": "Restroom",
   "Answer_5_Points": 7,
   "Answer_6": "To Eat",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 232,
   "Question_Title": "Name Something A Movie Star’s Kid Might Get As A Birthday Present.",
   "Answer_1": "Car",
   "Answer_1_Points": 36,
   "Answer_2": "Pet",
   "Answer_2_Points": 23,
   "Answer_3": "Money",
   "Answer_3_Points": 19,
   "Answer_4": "Jewelry",
   "Answer_4_Points": 12,
   "Answer_5": "House",
   "Answer_5_Points": 8,
   "Answer_6": "TV/Movie Role",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 233,
   "Question_Title": "Name A Food That It’s Hard To Keep Your Face Clean While Eating.",
   "Answer_1": "Ice Cream",
   "Answer_1_Points": 26,
   "Answer_2": "Ribs",
   "Answer_2_Points": 25,
   "Answer_3": "Spaghetti",
   "Answer_3_Points": 25,
   "Answer_4": "Sloppy Joe",
   "Answer_4_Points": 10,
   "Answer_5": "Pizza",
   "Answer_5_Points": 5,
   "Answer_6": "Watermelon",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 234,
   "Question_Title": "Name A Famous Movie Monster You Might See In A Black And White Film.",
   "Answer_1": "Godzilla",
   "Answer_1_Points": 63,
   "Answer_2": "King Kong",
   "Answer_2_Points": 31,
   "Answer_3": "Frankenstein",
   "Answer_3_Points": 16,
   "Answer_4": "Dracula",
   "Answer_4_Points": 7,
   "Answer_5": "Mummy",
   "Answer_5_Points": 5,
   "Answer_6": "Werewolf",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 235,
   "Question_Title": "Name The Most Stressful Holiday.",
   "Answer_1": "Christmas",
   "Answer_1_Points": 47,
   "Answer_2": "Valentine’s Day",
   "Answer_2_Points": 15,
   "Answer_3": "Thanksgiving",
   "Answer_3_Points": 13,
   "Answer_4": "New Year’s",
   "Answer_4_Points": 12,
   "Answer_5": "Halloween",
   "Answer_5_Points": 7,
   "Answer_6": "4th Of July",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 239,
   "Question_Title": "Name An Activity That Could Be Described As “Wholesome.”",
   "Answer_1": "Religous Activity",
   "Answer_1_Points": 25,
   "Answer_2": "Sports",
   "Answer_2_Points": 21,
   "Answer_3": "Reading",
   "Answer_3_Points": 18,
   "Answer_4": "Family Meals",
   "Answer_4_Points": 14,
   "Answer_5": "Board Games",
   "Answer_5_Points": 10,
   "Answer_6": "Baking/Cooking",
   "Answer_6_Points": 9
 },
 {
   "Question_ID": 240,
   "Question_Title": "Name An Animal That Children Are Excited By At The Zoo.",
   "Answer_1": "Monkey",
   "Answer_1_Points": 27,
   "Answer_2": "Lion",
   "Answer_2_Points": 25,
   "Answer_3": "Tiger",
   "Answer_3_Points": 22,
   "Answer_4": "Elephant",
   "Answer_4_Points": 11,
   "Answer_5": "Giraffe",
   "Answer_5_Points": 6,
   "Answer_6": "Bear",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 241,
   "Question_Title": "Name Something College Roommates Might Argue About.",
   "Answer_1": "Cleaning",
   "Answer_1_Points": 47,
   "Answer_2": "Food",
   "Answer_2_Points": 10,
   "Answer_3": "Money",
   "Answer_3_Points": 10,
   "Answer_4": "Space",
   "Answer_4_Points": 10,
   "Answer_5": "music",
   "Answer_5_Points": 7,
   "Answer_6": "Bedtime",
   "Answer_6_Points": 7
 },
 {
   "Question_ID": 242,
   "Question_Title": "Name A Type Of Service Person Who You Never Know How Much To Tip.",
   "Answer_1": "Server",
   "Answer_1_Points": 58,
   "Answer_2": "Valet service",
   "Answer_2_Points": 13,
   "Answer_3": "Hairdresser",
   "Answer_3_Points": 12,
   "Answer_4": "Taxi driver",
   "Answer_4_Points": 7,
   "Answer_5": "Bartender",
   "Answer_5_Points": 5,
   "Answer_6": "Bellhop",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 243,
   "Question_Title": "If You Were Stranded On A Tropical Island, Name Something You Might Have To Eat.",
   "Answer_1": "Coconuts",
   "Answer_1_Points": 35,
   "Answer_2": "Seafood",
   "Answer_2_Points": 19,
   "Answer_3": "Bananas",
   "Answer_3_Points": 14,
   "Answer_4": "Pineapples",
   "Answer_4_Points": 12,
   "Answer_5": "Bugs",
   "Answer_5_Points": 7,
   "Answer_6": "Berries",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 244,
   "Question_Title": "Who Or What Would You Not Want To Meet In The Middle Of A Hiking Trail?",
   "Answer_1": "Bear",
   "Answer_1_Points": 51,
   "Answer_2": "Snake",
   "Answer_2_Points": 24,
   "Answer_3": "Criminal",
   "Answer_3_Points": 12,
   "Answer_4": "Mountain Lion",
   "Answer_4_Points": 5,
   "Answer_5": "Wolf",
   "Answer_5_Points": 3,
   "Answer_6": "Big Foot",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 245,
   "Question_Title": "Name A Pet That Makes A Good Holiday Gift",
   "Answer_1": "Dog",
   "Answer_1_Points": 76,
   "Answer_2": "Cat",
   "Answer_2_Points": 12,
   "Answer_3": "Fish",
   "Answer_3_Points": 3,
   "Answer_4": "Rabbit",
   "Answer_4_Points": 2,
   "Answer_5": "Hamster",
   "Answer_5_Points": 2,
   "Answer_6": "Bird",
   "Answer_6_Points": 2
 },
 {
   "Question_ID": 246,
   "Question_Title": "Name A Pubic Place Where You Take Off Your Shoes.",
   "Answer_1": "Beach/Park",
   "Answer_1_Points": 35,
   "Answer_2": "Pool",
   "Answer_2_Points": 24,
   "Answer_3": "Shoe Store",
   "Answer_3_Points": 15,
   "Answer_4": "Gym",
   "Answer_4_Points": 11,
   "Answer_5": "Place Of Worship",
   "Answer_5_Points": 6,
   "Answer_6": "Bowling alley",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 248,
   "Question_Title": "Name A Person In Your Life Who It Would Be Unwise To Live With.",
   "Answer_1": "Parent",
   "Answer_1_Points": 43,
   "Answer_2": "Boss",
   "Answer_2_Points": 19,
   "Answer_3": "Sibling",
   "Answer_3_Points": 18,
   "Answer_4": "Ex",
   "Answer_4_Points": 10,
   "Answer_5": "Best Friend",
   "Answer_5_Points": 5,
   "Answer_6": "Boy/Girlfriend",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 249,
   "Question_Title": "What Is The Worst Thing To Forget On A Camping Trip?",
   "Answer_1": "Tent",
   "Answer_1_Points": 49,
   "Answer_2": "Sleeping Bag",
   "Answer_2_Points": 18,
   "Answer_3": "Food",
   "Answer_3_Points": 11,
   "Answer_4": "Water",
   "Answer_4_Points": 10,
   "Answer_5": "Matches",
   "Answer_5_Points": 6,
   "Answer_6": "Bug Spray",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 250,
   "Question_Title": "Instead Of A Horse, Which Animal Is It Hard To Imagine A Cowboy Riding?",
   "Answer_1": "Cow",
   "Answer_1_Points": 39,
   "Answer_2": "Dog",
   "Answer_2_Points": 22,
   "Answer_3": "Pig",
   "Answer_3_Points": 12,
   "Answer_4": "Donkey",
   "Answer_4_Points": 10,
   "Answer_5": "Elephant",
   "Answer_5_Points": 7,
   "Answer_6": "Camel",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 251,
   "Question_Title": "Name An Animal With Really Long Legs.",
   "Answer_1": "Giraffe",
   "Answer_1_Points": 59,
   "Answer_2": "Ostrich",
   "Answer_2_Points": 11,
   "Answer_3": "Frog",
   "Answer_3_Points": 9,
   "Answer_4": "Horse",
   "Answer_4_Points": 8,
   "Answer_5": "Gazelle",
   "Answer_5_Points": 7,
   "Answer_6": "Camel",
   "Answer_6_Points": 5
 },
 {
   "Question_ID": 252,
   "Question_Title": "Name Something People Buy, And Then Don’t Know How To Use.",
   "Answer_1": "Computer",
   "Answer_1_Points": 39,
   "Answer_2": "Cell Phone",
   "Answer_2_Points": 18,
   "Answer_3": "TV",
   "Answer_3_Points": 17,
   "Answer_4": "Camera",
   "Answer_4_Points": 9,
   "Answer_5": "DVD Player",
   "Answer_5_Points": 6,
   "Answer_6": "Car",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 253,
   "Question_Title": "Name Something A Little Girl Needs To Look Like A Princess.",
   "Answer_1": "Tiara",
   "Answer_1_Points": 63,
   "Answer_2": "Dress",
   "Answer_2_Points": 17,
   "Answer_3": "Magic Wand",
   "Answer_3_Points": 5,
   "Answer_4": "Makeup",
   "Answer_4_Points": 4,
   "Answer_5": "Jewelry",
   "Answer_5_Points": 3,
   "Answer_6": "Charm",
   "Answer_6_Points": 2
 },
 {
   "Question_ID": 254,
   "Question_Title": "Name A Board Game That You Wouldn’t Play If You Only Had An Hour.",
   "Answer_1": "Monopoly",
   "Answer_1_Points": 50,
   "Answer_2": "Life",
   "Answer_2_Points": 16,
   "Answer_3": "Scrabble",
   "Answer_3_Points": 11,
   "Answer_4": "Risk",
   "Answer_4_Points": 9,
   "Answer_5": "Chess",
   "Answer_5_Points": 5,
   "Answer_6": "Checkers",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 255,
   "Question_Title": "Besides Maple, Name A Flavor Of Syrup.",
   "Answer_1": "Blueberry",
   "Answer_1_Points": 46,
   "Answer_2": "Strawberry",
   "Answer_2_Points": 32,
   "Answer_3": "Raspberry",
   "Answer_3_Points": 4,
   "Answer_4": "Boisenberry",
   "Answer_4_Points": 4,
   "Answer_5": "Grape",
   "Answer_5_Points": 3,
   "Answer_6": "Cherry",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 257,
   "Question_Title": "Name A Chore People Do Most Often.",
   "Answer_1": "Wash Dishes",
   "Answer_1_Points": 42,
   "Answer_2": "Laundry",
   "Answer_2_Points": 16,
   "Answer_3": "Vacuum",
   "Answer_3_Points": 12,
   "Answer_4": "Cook",
   "Answer_4_Points": 9,
   "Answer_5": "Sweep",
   "Answer_5_Points": 7,
   "Answer_6": "Clean Bathroom",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 258,
   "Question_Title": "Name Something People Do When They Want To Look Better. (Makeover Is Not An Answer, Be More Specific)",
   "Answer_1": "Change Hair",
   "Answer_1_Points": 28,
   "Answer_2": "Diet",
   "Answer_2_Points": 25,
   "Answer_3": "Put On Makeup",
   "Answer_3_Points": 20,
   "Answer_4": "Plastic Surgery",
   "Answer_4_Points": 13,
   "Answer_5": "Exercise",
   "Answer_5_Points": 5,
   "Answer_6": "Clean Up",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 259,
   "Question_Title": "Name Something That You Have To Do Sometimes That a Billionaire Has Probably Never Done.",
   "Answer_1": "Low End Job",
   "Answer_1_Points": 30,
   "Answer_2": "Clean/Laundry",
   "Answer_2_Points": 26,
   "Answer_3": "Borrow Money",
   "Answer_3_Points": 17,
   "Answer_4": "Fly Economy",
   "Answer_4_Points": 8,
   "Answer_5": "Buy Used",
   "Answer_5_Points": 8,
   "Answer_6": "Clip Coupons",
   "Answer_6_Points": 6
 },
 {
   "Question_ID": 260,
   "Question_Title": "If A Husband Found Out That His Wife Had A Bad Day At Work, Name Something He Might Do To Make Her Feel Better.",
   "Answer_1": "Cook Dinner",
   "Answer_1_Points": 48,
   "Answer_2": "Give A Massage",
   "Answer_2_Points": 17,
   "Answer_3": "Giver Her Flowers",
   "Answer_3_Points": 16,
   "Answer_4": "Prepare A Bath",
   "Answer_4_Points": 8,
   "Answer_5": "take Her Out",
   "Answer_5_Points": 4,
   "Answer_6": "Comfort Her",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 261,
   "Question_Title": "What Might An Actor Do To Cure Stage Fright?",
   "Answer_1": "Have A drink",
   "Answer_1_Points": 38,
   "Answer_2": "rehearse",
   "Answer_2_Points": 32,
   "Answer_3": "Imagine crowd Naked",
   "Answer_3_Points": 12,
   "Answer_4": "Deep Breaths",
   "Answer_4_Points": 5,
   "Answer_5": "Mediate",
   "Answer_5_Points": 5,
   "Answer_6": "Count To 10",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 263,
   "Question_Title": "Name A Job That Ends With The Word “Guard.”",
   "Answer_1": "Lifeguard",
   "Answer_1_Points": 34,
   "Answer_2": "Security Guard",
   "Answer_2_Points": 27,
   "Answer_3": "Bodyguard",
   "Answer_3_Points": 19,
   "Answer_4": "Prison Guard",
   "Answer_4_Points": 7,
   "Answer_5": "National Guard",
   "Answer_5_Points": 5,
   "Answer_6": "Crossing Guard",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 276,
   "Question_Title": "Name A Food That You Become Very Thirsty While Eating.",
   "Answer_1": "Chips",
   "Answer_1_Points": 28,
   "Answer_2": "Popcorn",
   "Answer_2_Points": 25,
   "Answer_3": "Peanuts",
   "Answer_3_Points": 12,
   "Answer_4": "Pizza",
   "Answer_4_Points": 10,
   "Answer_5": "Crackers",
   "Answer_5_Points": 5,
   "Answer_6": "Ice Cream",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 300,
   "Question_Title": "Name Something Models And Wrestlers Both Do.",
   "Answer_1": "Pose",
   "Answer_1_Points": 35,
   "Answer_2": "Work Out",
   "Answer_2_Points": 30,
   "Answer_3": "Act",
   "Answer_3_Points": 13,
   "Answer_4": "Dress Up",
   "Answer_4_Points": 8,
   "Answer_5": "Fight",
   "Answer_5_Points": 7,
   "Answer_6": "Strut",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 301,
   "Question_Title": "Name An Animal That’s Often Described As “Beautiful.”",
   "Answer_1": "Cat",
   "Answer_1_Points": 30,
   "Answer_2": "Deer",
   "Answer_2_Points": 20,
   "Answer_3": "Horse",
   "Answer_3_Points": 19,
   "Answer_4": "Bird",
   "Answer_4_Points": 13,
   "Answer_5": "lion",
   "Answer_5_Points": 9,
   "Answer_6": "swan",
   "Answer_6_Points": 3
 },
 {
   "Question_ID": 302,
   "Question_Title": "What Item Do People Always Keep Inside Their Cars?",
   "Answer_1": "Flashlight",
   "Answer_1_Points": 30,
   "Answer_2": "Map",
   "Answer_2_Points": 18,
   "Answer_3": "Umbrella",
   "Answer_3_Points": 14,
   "Answer_4": "Registration",
   "Answer_4_Points": 13,
   "Answer_5": "Sunglasses",
   "Answer_5_Points": 11,
   "Answer_6": "Tissues",
   "Answer_6_Points": 8
 },
 {
   "Question_ID": 305,
   "Question_Title": "We Asked 100 Wives: If Your Husband Were The Incredible Hulk, Tell Me What Would Turn Him Into A Monster.",
   "Answer_1": "Money/Bills",
   "Answer_1_Points": 36,
   "Answer_2": "Chores/Nagging",
   "Answer_2_Points": 22,
   "Answer_3": "Jealousy",
   "Answer_3_Points": 15,
   "Answer_4": "No/Bad Food",
   "Answer_4_Points": 13,
   "Answer_5": "Naughty Kids",
   "Answer_5_Points": 6,
   "Answer_6": "Traffic",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 309,
   "Question_Title": "Name The Heaviest Item You Buy At The Supermarket.",
   "Answer_1": "Watermelon",
   "Answer_1_Points": 24,
   "Answer_2": "Milk",
   "Answer_2_Points": 17,
   "Answer_3": "Potatoes",
   "Answer_3_Points": 15,
   "Answer_4": "Turkey",
   "Answer_4_Points": 14,
   "Answer_5": "Pet Food",
   "Answer_5_Points": 13,
   "Answer_6": "Water",
   "Answer_6_Points": 10
 },
 {
   "Question_ID": 310,
   "Question_Title": "What Should A Spy Avoid Wearing, If He Doesn’t Want To Be Identified By His Profession?",
   "Answer_1": "Sunglasses",
   "Answer_1_Points": 39,
   "Answer_2": "Hat",
   "Answer_2_Points": 19,
   "Answer_3": "Trench Coat",
   "Answer_3_Points": 18,
   "Answer_4": "Wig",
   "Answer_4_Points": 9,
   "Answer_5": "Badge",
   "Answer_5_Points": 5,
   "Answer_6": "Weapon",
   "Answer_6_Points": 4
 },
 {
   "Question_ID": 311,
   "Question_Title": "If You Were Filling In For Santa, Name Something You’d Have To Learn How To Do.",
   "Answer_1": "Say Ho Ho Ho",
   "Answer_1_Points": 42,
   "Answer_2": "Drive A Sleigh",
   "Answer_2_Points": 21,
   "Answer_3": "Climb Down Chimney",
   "Answer_3_Points": 11,
   "Answer_4": "made A List",
   "Answer_4_Points": 8,
   "Answer_5": "Work With Reindeer",
   "Answer_5_Points": 7,
   "Answer_6": "Wear His Suit",
   "Answer_6_Points": 4
 }
]